ALTER TABLE [PAPER_NEW].[DBO].[PP_LOGO_OPTION_TB] ADD WAIT_TITLE VARCHAR(500) NULL
ALTER TABLE [PAPER_NEW].[DBO].[PP_LOGO_OPTION_TB] ADD WAIT_COMPANY VARCHAR(100) NULL
ALTER TABLE [PAPER_NEW].[DBO].[PP_LOGO_OPTION_TB] ADD PUB_LOGO_BYTE INT NOT NULL DEFAULT 0