  
/*************************************************************************************  
 *  단위 업무 명 : 스피드 옵션 광고리스트(구인지역별 페이지)  
 *  작   성   자 : 최 병찬  
 *  작   성   일 : 2014/04/10  
 *  수   정   자 : 김선호  
 *  수   정   일 : 2021/02/05  
 *  수 정  내 용 : 공고의 노출지역 총 갯수 업데이트(AREA_COUNT)  
 *  수   정   자 : 방순현        
 *  수   정   일 : 2021/10/12 
 *  수 정 내  용 : 로고검수 프로세스 개선
 *  설        명 :  
 *  주 의  사 항 :  
 *  사 용  소 스 :  
 *  사 용  예 제 :  
                EXEC GET_F_AD_SPEED_INFO_OPTION_LIST_JOB_AREA_PROC 1,'401','','','',1,0,25  
                EXEC GET_F_AD_SPEED_INFO_OPTION_LIST_JOB_AREA_PROC 3,'4010101, 4010103, 4010106','서울','','',1,0,0  
                exec GET_F_AD_SPEED_INFO_OPTION_LIST_JOB_AREA_PROC 0,'','인천','','',1,default,default,0  
                EXEC GET_F_AD_SPEED_INFO_OPTION_LIST_JOB_AREA_PROC_BK01 1,'408','','','',3,6,0  
                exec GET_F_AD_SPEED_INFO_OPTION_LIST_JOB_AREA_PROC 2,'40305','서울','노원구','',1,default,default,0  
                exec GET_F_AD_SPEED_INFO_OPTION_LIST_JOB_AREA_PROC_BK01 2,'40305','서울','노원구','',1,default,default,0  
  
                EXEC GET_F_AD_SPEED_INFO_OPTION_LIST_JOB_AREA_PROC 1,'401','','','',1,0,180,0  
                GET_F_AD_SPEED_INFO_OPTION_LIST_JOB_AREA_PROC_BAK190909 0,'','12','1201','12010002',1,0,180,0  
                EXEC GET_F_AD_SPEED_INFO_OPTION_LIST_JOB_AREA_PROC 1,'401','서울','강남구','',1,0,180,0  
 *************************************************************************************/  
ALTER PROCEDURE [dbo].[GET_F_AD_SPEED_INFO_OPTION_LIST_JOB_AREA_PROC]  
   @LEVEL        INT        = 0   -- 분류레벨  
 , @FINDCODE     VARCHAR(100) = ''   -- 인터넷 통합코드  
 , @METRO       VARCHAR(100)  = ''   -- 검색 시,도  
 , @CITY        VARCHAR(100)  = ''   -- 검색 구,군  
 , @DONG        VARCHAR(100)  = ''   -- 검색 동,읍,면  
 , @REGTERM     INT        = 1   -- 기간 1:전체기간 0:오늘등록 3: 3일내 등록 7:7일내 등록  
 , @TIME        INT        = 0   -- 시간대 1:오전(06:00~12:00) 2:오후(12:00~18:00) 3:저녁(18:00~24:00) 4:새벽(00:00~06:00) 5:시간협의 6:풀타임(8시간 이상)  
  , @LAYOUT_BRANCH  TINYINT       = 180   -- LAYOUT_BRANCH  (기존 지점코드)  
  , @SUB_BRANCH     INT           = 0     -- SubBranchCode  (신지점코드)  
  
AS  
  
BEGIN  
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED  
 SET NOCOUNT ON  
  
 DECLARE @SQL NVARCHAR(MAX)  
 DECLARE @WHERE_SQL NVARCHAR(MAX)  
 DECLARE @JOIN_LINE_SQL NVARCHAR(MAX)  
 DECLARE @TIME_TABLE_FIELD NVARCHAR(MAX)  
 DECLARE @TIME_FIELD NVARCHAR(MAX)  
 DECLARE @TIME_LINE_TABLE NVARCHAR(MAX)  
 DECLARE @ORDERBY_SQL VARCHAR(MAX)  
 DECLARE @SQL_PARAM NVARCHAR(MAX)  
  
  DECLARE @SQL_SUB NVARCHAR(MAX)  
  DECLARE @SQL_SPEED NVARCHAR(MAX)  
  DECLARE @SQL_SPEEDHOT NVARCHAR(MAX)  
  DECLARE @SQL_SPEEDLIST NVARCHAR(MAX)  
  DECLARE @OPT_SQL NVARCHAR(1000)  
  
  DECLARE @MAXLOOP_COUNT      INT  
  DECLARE @LOOP_COUNT         INT  
  DECLARE @WHEREMULTI         NVARCHAR(MAX)  
  DECLARE @__FINDCODE         INT  
  DECLARE @__AREA_A           VARCHAR(20)  
  DECLARE @__AREA_B           VARCHAR(20)  
  DECLARE @__AREA_C           VARCHAR(20)  
  
 SET @SQL = ''  
 SET @WHERE_SQL = ''  
 SET @JOIN_LINE_SQL = ''  
 SET @TIME_TABLE_FIELD = ''  
 SET @TIME_FIELD = ''  
 SET @TIME_LINE_TABLE = ''  
 SET @ORDERBY_SQL = ' ORDER BY SORT, NEWID() '  
  
  SET @SQL_SUB = ''  
  SET @SQL_SPEED = ''  
  SET @SQL_SPEEDHOT = ''  
  SET @SQL_SPEEDLIST = ''  
  
  SET @MAXLOOP_COUNT = 0  
  SET @LOOP_COUNT = 1  
  SET @WHEREMULTI = ''  
  SET @__AREA_A = ''  
  SET @__AREA_B = ''   
  SET @__AREA_C = ''   
  
  -- 지역판 조건  
  IF @SUB_BRANCH > 0  
    BEGIN  
     SELECT @OPT_SQL =  COALESCE(@OPT_SQL+',' , '')  + CAST(GOOD_ID as varchar)  
       FROM DBO.FN_PKGIDTOGOODID(14,'PD','L',5000)  
        SET @SQL_SPEED = ' OPT_AREA&2=2 AND OPT_CODE IN ('+@OPT_SQL+') '  
    END  
  ELSE  
    BEGIN  
     --SELECT @OPT_SQL =  COALESCE(@OPT_SQL+',' , '')  + CAST(GOOD_ID as varchar)  
     --  FROM DBO.FN_PKGIDTOGOODID(14,'N','L',4000)  
      SELECT @OPT_SQL = COALESCE(@OPT_SQL+',' , '') + CAST(GOODS_ID AS VARCHAR)   
        FROM PP_JOB_AD_GOODS_POSITION_ENTITY_TB (NOLOCK)  
       WHERE POSITION_CODE = 'WJ010301'  
             
      SET @SQL_SPEED = ' OPT_AREA&1=1 AND OPT_CODE IN ('+@OPT_SQL+') '  
    --SET @SQL_SPEED = ' OPT_AREA&1=1 AND OPT_CODE IN ((SELECT GOODS_ID FROM PP_JOB_AD_GOODS_POSITION_ENTITY_TB WHERE POSITION_CODE = ''WJ010301'')) '  
    END  
  
 --분류 검색  
  /*  
 IF @LEVEL <> '' AND @FINDCODE <> ''  
 BEGIN  
  SET @JOIN_LINE_SQL = @JOIN_LINE_SQL + ' JOIN PP_LINE_AD_FINDCODE_1DAY_TB AS B WITH(NOLOCK) ON B.LINEADID = A.LINEADID AND B.INPUT_BRANCH = A.INPUT_BRANCH AND B.LAYOUT_BRANCH = A.LAYOUT_BRANCH '  
  
    IF @LEVEL = 1  
      SET @WHERE_SQL = @WHERE_SQL + ' AND B.FINDCODE BETWEEN @FINDCODE * 10000  AND @FINDCODE * 10000 + 9999 '  
    ELSE IF @LEVEL = 2  
      SET @WHERE_SQL = @WHERE_SQL + ' AND B.FINDCODE BETWEEN @FINDCODE * 100 AND @FINDCODE *100 + 99 '  
    ELSE IF @LEVEL = 3  
    BEGIN  
      IF CHARINDEX(',', @FINDCODE) > 0  
        SET @WHERE_SQL = @WHERE_SQL + ' AND B.FINDCODE IN (' + @FINDCODE + ')'  
      ELSE  
        SET @WHERE_SQL = @WHERE_SQL + ' AND B.FINDCODE = @FINDCODE '  
    END  
 END  
  */  
  
  --FJ001-102 업직종 다중 선택     
  IF @FINDCODE <> ''  
  BEGIN  
    SET @JOIN_LINE_SQL = @JOIN_LINE_SQL + ' JOIN PP_LINE_AD_FINDCODE_1DAY_TB AS B WITH(NOLOCK) ON B.LINEADID = A.LINEADID AND B.INPUT_BRANCH = A.INPUT_BRANCH AND B.LAYOUT_BRANCH = A.LAYOUT_BRANCH '  
  
    IF CHARINDEX(',', @FINDCODE) > 0  
    BEGIN  
      SET @WHEREMULTI = ' AND ('  
      SET @MAXLOOP_COUNT = DBO.FN_CHAR_COUNT(@FINDCODE, ',') + 1  
      WHILE @LOOP_COUNT <= @MAXLOOP_COUNT  
      BEGIN  
        SET @__FINDCODE = DBO.FN_SPLIT_NEW(@FINDCODE, @LOOP_COUNT, ',')  
  
        IF LEN(@__FINDCODE) = 3 --대분류  
          SET @WHEREMULTI = @WHEREMULTI + '(B.FINDCODE BETWEEN ' + CONVERT(VARCHAR, @__FINDCODE * 10000)  + ' AND ' + CONVERT(VARCHAR, @__FINDCODE * 10000 + 9999) + ')'  
        ELSE IF LEN(@__FINDCODE) = 5 --중분류  
          SET @WHEREMULTI = @WHEREMULTI + '(B.FINDCODE BETWEEN ' + CONVERT(VARCHAR, @__FINDCODE * 100)  + ' AND ' + CONVERT(VARCHAR, @__FINDCODE * 100 + 99) + ')'  
        ELSE IF LEN(@__FINDCODE) = 7 --소분류  
          SET @WHEREMULTI = @WHEREMULTI + '(B.FINDCODE = ' + CONVERT(VARCHAR, @__FINDCODE) + ')'  
  
        SET @LOOP_COUNT += 1  
        IF @LOOP_COUNT <= @MAXLOOP_COUNT          
          SET @WHEREMULTI = @WHEREMULTI + ' OR '  
        ELSE  
          SET @WHEREMULTI = @WHEREMULTI + ') '  
      END  
    END  
    ELSE  
    BEGIN  
      IF LEN(@FINDCODE) = 3 --대분류  
        SET @WHERE_SQL = @WHERE_SQL + ' AND B.FINDCODE BETWEEN @FINDCODE * 10000  AND @FINDCODE * 10000 + 9999 '  
      ELSE IF LEN(@FINDCODE) = 5 --중분류  
        SET @WHERE_SQL = @WHERE_SQL + ' AND B.FINDCODE BETWEEN @FINDCODE * 100 AND @FINDCODE *100 + 99 '  
      ELSE IF LEN(@FINDCODE) = 7 --소분류  
        SET @WHERE_SQL = @WHERE_SQL + ' AND B.FINDCODE = @FINDCODE '  
    END  
  
  END  
  SET @WHERE_SQL = @WHERE_SQL + @WHEREMULTI  
  
 -- 지역 검색  
  /*  
 IF @METRO <> ''  
  BEGIN  
   IF @CITY <> ''  
   BEGIN  
    IF @DONG <> ''  
    BEGIN  
     IF CHARINDEX(',', @DONG) > 0  
      SET @WHERE_SQL = @WHERE_SQL + ' AND C.AREA_A=@METRO AND C.AREA_B=@CITY AND C.AREA_C IN (''' + REPLACE(@DONG,',',''',''') + ''')'  
     ELSE  
      SET @WHERE_SQL = @WHERE_SQL + ' AND C.AREA_A=@METRO AND C.AREA_B=@CITY AND C.AREA_C = @DONG '  
    END  
    ELSE  
    BEGIN  
     SET @WHERE_SQL = @WHERE_SQL + ' AND C.AREA_A=@METRO AND C.AREA_B=@CITY '  
    END  
   END  
   ELSE  
   BEGIN  
    SET @WHERE_SQL = @WHERE_SQL + ' AND C.AREA_A=@METRO '  
   END  
  END  
  ELSE  
  BEGIN  
    IF @SUB_BRANCH > 0  
    BEGIN  
      -- 시/도 매핑 지역  
      IF ISNULL((SELECT TOP 1 AREA_B FROM CC_BRANCH_AREA_TB WHERE SUB_BRANCHCODE = @SUB_BRANCH),'') = ''  
        SET @JOIN_LINE_SQL = @JOIN_LINE_SQL + ' JOIN CC_BRANCH_AREA_TB AS BA WITH(NOLOCK) ON BA.AREA_A = C.AREA_A AND BA.SUB_BRANCHCODE = @SUB_BRANCH '  
      ELSE  -- 시/도 + 구/군 매핑 지역  
        SET @JOIN_LINE_SQL = @JOIN_LINE_SQL + ' JOIN CC_BRANCH_AREA_TB AS BA WITH(NOLOCK) ON BA.AREA_A = C.AREA_A AND BA.AREA_B = C.AREA_B AND BA.SUB_BRANCHCODE = @SUB_BRANCH'  
    END  
  END  
  */  
  
  --FJ001-102 주소 다중 선택    
  IF @METRO <> ''  
  BEGIN  
    IF CHARINDEX(',', @METRO) > 0  
    BEGIN  
      SET @WHEREMULTI = @WHEREMULTI + ' AND ('  
      SET @MAXLOOP_COUNT = DBO.FN_CHAR_COUNT(@METRO, ',') + 1  
      SET @LOOP_COUNT = 1  
      WHILE @LOOP_COUNT <= @MAXLOOP_COUNT  
      BEGIN  
        SET @__AREA_A = DBO.FN_SPLIT_NEW(@METRO, @LOOP_COUNT, ',')  
        SET @__AREA_B = DBO.FN_SPLIT_NEW(@CITY, @LOOP_COUNT, ',')  
        SET @__AREA_C = DBO.FN_SPLIT_NEW(@DONG, @LOOP_COUNT, ',')  
  
        SET @WHEREMULTI = @WHEREMULTI + '('  
        IF @__AREA_C <> ''            
          SET @WHEREMULTI = @WHEREMULTI + 'C.AREA_C_GROUP = ''' + @__AREA_C + ''' '            
        ELSE IF @__AREA_B <> ''  
          SET @WHEREMULTI = @WHEREMULTI + 'C.AREA_B_CODE = ''' + @__AREA_B + ''' '            
        ELSE IF @__AREA_A <> ''  
          SET @WHEREMULTI = @WHEREMULTI + 'C.AREA_A_CODE = ''' + @__AREA_A + ''' '          
  
        SET @WHEREMULTI = @WHEREMULTI + ')'  
  
        SET @LOOP_COUNT += 1  
        IF @LOOP_COUNT <= @MAXLOOP_COUNT          
          SET @WHEREMULTI = @WHEREMULTI + ' OR '  
        ELSE  
          SET @WHEREMULTI = @WHEREMULTI + ') '  
      END  
    END  
    ELSE  
    BEGIN  
      IF @DONG <> ''  
        SET @WHEREMULTI = @WHEREMULTI + ' AND C.AREA_C_GROUP = @DONG '  
      ELSE IF @CITY <> ''  
        SET @WHEREMULTI = @WHEREMULTI + ' AND C.AREA_B_CODE = @CITY '  
      ELSE IF @METRO <> ''  
        SET @WHEREMULTI = @WHEREMULTI + ' AND C.AREA_A_CODE = @METRO '        
  --SET @WHEREMULTI = @WHEREMULTI + ')'  
    END  
    SET @WHERE_SQL = @WHERE_SQL + @WHEREMULTI  
  END  
  ELSE  
  BEGIN  
    IF @SUB_BRANCH > 0  
    BEGIN  
      -- 시/도 매핑 지역  
      IF ISNULL((SELECT TOP 1 AREA_B FROM CC_BRANCH_AREA_TB WHERE SUB_BRANCHCODE = @SUB_BRANCH),'') = ''  
        SET @JOIN_LINE_SQL = @JOIN_LINE_SQL + ' JOIN CC_BRANCH_AREA_TB AS BA WITH(NOLOCK) ON BA.AREA_A = C.AREA_A AND BA.SUB_BRANCHCODE = @SUB_BRANCH '  
      ELSE  -- 시/도 + 구/군 매핑 지역  
        SET @JOIN_LINE_SQL = @JOIN_LINE_SQL + ' JOIN CC_BRANCH_AREA_TB AS BA WITH(NOLOCK) ON BA.AREA_A = C.AREA_A AND BA.AREA_B = C.AREA_B AND BA.SUB_BRANCHCODE = @SUB_BRANCH'  
    END  
  END    
  
 -- 기간 검색  
 IF @REGTERM <> 1  
 BEGIN  
    IF @REGTERM = 0  
      SET @WHERE_SQL = @WHERE_SQL + ' AND A.START_DT >= CONVERT(VARCHAR(10), DATEADD(DAY, -1, GETDATE()), 120)'  
    ELSE  
      SET @WHERE_SQL = @WHERE_SQL + ' AND A.START_DT >= CONVERT(VARCHAR(10), DATEADD(DAY, ' + CAST(@REGTERM * -1 AS VARCHAR(10)) + ', GETDATE()), 120)'  
 END  
  
  
 -- 시간대별 검색  
 -- 1:오전(06:00~12:00) 2:오후(12:00~18:00) 3:저녁(18:00~24:00) 4:새벽(00:00~06:00) 5:시간협의 6:풀타임(8시간 이상)  
 IF @TIME > 0  
 BEGIN  
  SET @JOIN_LINE_SQL = @JOIN_LINE_SQL + ' JOIN PP_LINE_AD_EXTEND_DETAIL_JOB_1DAY_TB AS F WITH(NOLOCK) ON F.LINEADID = A.LINEADID AND F.INPUT_BRANCH = A.INPUT_BRANCH AND F.LAYOUT_BRANCH = A.LAYOUT_BRANCH '  
  
  IF @TIME = 4  
   SET @WHERE_SQL = @WHERE_SQL + ' AND (F.WORKTIMEFROM>=2300 OR F.WORKTIMEFROM<=600) AND (F.WORKTIMETO>=100 AND F.WORKTIMETO<=900) '  
  ELSE IF @TIME = 1  
   SET @WHERE_SQL = @WHERE_SQL + ' AND (F.WORKTIMEFROM>=500 AND F.WORKTIMEFROM<=1200) AND ( F.WORKTIMETO>=600 AND F.WORKTIMETO<=1500) '  
  ELSE IF @TIME = 2  
   SET @WHERE_SQL = @WHERE_SQL + ' AND (F.WORKTIMEFROM>=1100 AND F.WORKTIMEFROM<=1800) AND ( F.WORKTIMETO>=1200 AND F.WORKTIMETO<=2100) '  
  ELSE IF @TIME = 3  
   SET @WHERE_SQL = @WHERE_SQL + ' AND (F.WORKTIMEFROM>=1700 AND F.WORKTIMEFROM<=2300) AND ( F.WORKTIMETO>=1800 OR F.WORKTIMETO<=300) '  
  ELSE IF @TIME = 6  
      SET @WHERE_SQL = @WHERE_SQL + ' AND CASE WHEN F.WORKTIMEFROM > F.WORKTIMETO THEN CASE WHEN (F.WORKTIMETO+2400)-F.WORKTIMEFROM >= 800 THEN 1 ELSE 0 END ELSE CASE WHEN F.WORKTIMETO-F.WORKTIMEFROM >= 800 THEN 1 ELSE 0 END END = 1'  
 END  
 ELSE  
 BEGIN  
  SET @TIME_LINE_TABLE = ''  
 END  
  
  -- 스피드  
 SET @SQL = '  
SELECT B.LINEADID,B.INPUT_BRANCH,B.LAYOUT_BRANCH,B.AD_KIND  
,CASE WHEN LEN(LTRIM(RTRIM(ISNULL(B.TITLE, '''')))) = 0 THEN  
      CASE WHEN LEN(LTRIM(RTRIM(ISNULL(B.FIELD_2, '''')))) = 0 THEN  
          CASE WHEN LEN(LTRIM(RTRIM(ISNULL(B.CONTENTS, '''')))) = 0 THEN DBO.FN_SPLIT(B.FINDCODENAME,''>'', 3) + '' 모집''  
          ELSE B.CONTENTS  
          END  
      ELSE B.FIELD_2  
      END  
ELSE DBO.fn_DelSpecCharTitle(ISNULL(C.WAIT_TITLE , ISNULL(B.TITLE , C.MAIN_TITLE)), B.[VERSION])  
END AS TITLE  
,'''' AS CONTENTS
,E.AREA_A
,E.AREA_B
,dbo.fn_DelSpecCharTitle(ISNULL(C.WAIT_COMPANY , ISNULL(B.FIELD_6 , C.MAIN_COMPANY)),B.[VERSION]) AS FIELD_6
,B.REG_DT
,D.PAYF
,D.PAYFROM
,D.PAYTO
,B.START_DT
,B.FINDCODE
,E.AREA_C
,C.PUB_CONFIRM
,ISNULL(C.WAIT_LOGO , DBO.FN_ISNULL(C.PUB_LOGO , C.MAIN_LOGO)) AS PUB_LOGO
,B.VERSION
,B.DISPLAY_OPT
,B.ICON_OPT
,B.OPT_PATH  
,B.LINEADNO  
,B.USER_ID  
,CASE WHEN B.DISPLAY_OPT & 1 = 1 THEN 1 ELSE 2 END AS SORT  
,D.RECRUIT_END_DT  
,D.REGULAREMPF  
,D.SEXF  
,D.AGEF  
,D.AGEFROM  
,D.AGETO  
,D.WORKTIMEF  
,D.WORKTIMEFROM  
,D.WORKTIMETO  
,B.CUID  
,D.PAY_COMPANY_RULES  
,E.AREA_COUNT  
  FROM (  
        SELECT A.LINEADNO, A.LINEADID,A.INPUT_BRANCH,A.LAYOUT_BRANCH,MIN(C.[ORDER]) AS [ORDER]  
          FROM PP_LINE_AD_TB AS A WITH(NOLOCK)  
          JOIN PP_LINE_AD_AREA_1DAY_TB AS C WITH(NOLOCK) ON C.LINEADID = A.LINEADID AND C.INPUT_BRANCH = A.INPUT_BRANCH AND C.LAYOUT_BRANCH = A.LAYOUT_BRANCH  
         ' + @JOIN_LINE_SQL + '  
         WHERE A.GROUP_CD = 14 AND A.OPT_START_DT <= CONVERT(VARCHAR(10),GETDATE(),121) AND A.OPT_END_DT >= DATEADD(DAY,-1,GETDATE())  
           AND A.IDENTYFLAG = ''1''  
           AND' + @SQL_SPEED + '  
         ' + @WHERE_SQL + '  
         GROUP BY A.LINEADNO, A.LINEADID,A.INPUT_BRANCH,A.LAYOUT_BRANCH  
       ) X  
JOIN PP_LINE_AD_TB AS B WITH(NOLOCK) ON B.LINEADID = X.LINEADID AND B.INPUT_BRANCH = X.INPUT_BRANCH AND B.LAYOUT_BRANCH = X.LAYOUT_BRANCH  
JOIN PP_LINE_AD_AREA_1DAY_TB AS E WITH(NOLOCK) ON E.LINEADID = X.LINEADID AND E.INPUT_BRANCH = X.INPUT_BRANCH AND E.LAYOUT_BRANCH = X.LAYOUT_BRANCH AND E.[ORDER]=X.[ORDER]  
JOIN PP_LINE_AD_EXTEND_DETAIL_JOB_1DAY_TB D WITH(NOLOCK) ON D.LINEADID = X.LINEADID AND D.INPUT_BRANCH = X.INPUT_BRANCH AND D.LAYOUT_BRANCH = X.LAYOUT_BRANCH  
LEFT JOIN PP_LOGO_OPTION_TB AS C WITH(NOLOCK) ON C.LINEADID = X.LINEADID AND C.INPUT_BRANCH = X.INPUT_BRANCH AND C.LAYOUT_BRANCH = X.LAYOUT_BRANCH  
'  
  SET @SQL = @SQL + @ORDERBY_SQL + ';'  
 SET @SQL_PARAM = '  
 @LEVEL        INT  
 , @FINDCODE     VARCHAR(100)  
 , @METRO       VARCHAR(30)  
 , @CITY        VARCHAR(30)  
 , @DONG        VARCHAR(50)  
 , @REGTERM     INT  
 , @TIME        INT  
  , @LAYOUT_BRANCH  TINYINT  
  , @SUB_BRANCH     INT  
'  
  
 PRINT @SQL  
 EXECUTE SP_EXECUTESQL @SQL,@SQL_PARAM,  
 @LEVEL  
 , @FINDCODE  
 , @METRO  
 , @CITY  
 , @DONG  
 , @REGTERM  
 , @TIME  
 , @LAYOUT_BRANCH  
 , @SUB_BRANCH  
  
END  
  
  
  
  
  