
/*************************************************************************************
 *  단위 업무 명 : 모바일 구인구직 상품관련 노출
 *  작   성   자 :
 *  작   성   일 :
 *  수   정   자 : 김선호
 *  수   정   일 : 2021/02/16
 *  수 정  내 용 : 공고의 노출지역 총 갯수 업데이트(AREA_COUNT)
 *  수   정   자 : 방 순 현        
 *  수   정   일 : 2021/10/12 
 *  수 정 내  용 : 로고검수 프로세스 개선
 *  설        명 :
 *  주 의  사 항 :
 *  사 용  소 스 :
 *  사 용  예 제 :
 EXEC MB_JOB_GET_MAIN_OPT_LIST
*************************************************************************************/
ALTER PROC [dbo].[MB_JOB_GET_MAIN_OPT_LIST]
AS
BEGIN

 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
 SET NOCOUNT ON;

   SELECT 
     A.LINEADNO, A.LINEADID, A.INPUT_BRANCH, A.LAYOUT_BRANCH, A.AD_KIND, A.GROUP_CD, A.[VERSION]
    , ISNULL(A.FINDCODE, 4010000) AS FINDCODE
    , dbo.fn_DelSpecCharTitle(A.TITLE,A.[VERSION]) AS TITLE
    , A.CONTENTS
    , ISNULL(L.MAIN_TITLE, '') AS MAIN_TITLE
    , ISNULL(L.MAIN_COMPANY, '') AS MAIN_COMPANY
    , A.DETAILADCODE
    , A.ORDER_NAME
    , A.FIELD_2, dbo.fn_DelSpecCharTitle(A.FIELD_6,A.[VERSION]) AS FIELD_6
    , A.FINDCODENAME2 AS CODENM2, A.FINDCODENAME3 AS CODENM3, A.FINDCODENAME4 AS CODENM4
    , A.PAYF, A.PAYFROM, A.PAYTO
    , ISNULL(E.PAY_POSSIBLE, 0) AS PAY_POSSIBLE, ISNULL(E.PAY_COMPANY_RULES, 0) AS PAY_COMPANY_RULES, ISNULL(E.PAY_COMPANY_RULES_ETC, '') AS PAY_COMPANY_RULES_ETC
    , A.AREA_A, A.AREA_B, A.AREA_C, A.AREA_DONG
    , DATEDIFF(DAY, A.RECRUIT_END_DT, GETDATE()) AS DDAY
    , E.REGULAREMPF
    , A.RECRUIT_END_DT
    , A.OPT_CODE
    , A.PAPER_OPT
    , A.MOBILE_OPT_CODE
    , A.GMAP_X, A.GMAP_Y
    , A.VNSUSEF, A.VNSNO, A.PHONE, A.PHONE_MOBILE
    , ISNULL(E.PHONEF, 0) AS PHONEF
    , E.MOBILE
    , ISNULL(E.PHONE1_VIEWF,0) AS PHONE1_VIEWF
    , E.PHONE1
    , ISNULL(E.PHONE2_VIEWF,0) AS PHONE2_VIEWF
    , E.PHONE2
    , A.MOBILEF
    , ISNULL(L.PUB_CONFIRM, '0') AS PUB_CONFIRM
    , dbo.FN_ISNULL(L.MAIN_LOGO , L.PUB_LOGO) AS MAIN_LOGO
    , ISNULL(GOODS_MAIN_POSITION, 0) AS GOODS_MAIN_POSITION
    , ISNULL(GOODS_SUB_MAIN_POSITION, 0) AS GOODS_SUB_MAIN_POSITION
    , ISNULL(GOODS_SUB_LIST_POSITION, 0) AS GOODS_SUB_LIST_POSITION
    , B.AREA_COUNT
   FROM MOBILE_JOB_GOOD_TB AS A WITH(NOLOCK) 
   INNER JOIN PP_LINE_AD_AREA_1DAY_TB AS B WITH(NOLOCK) ON B.LINEADID = A.LINEADID AND B.INPUT_BRANCH = A.INPUT_BRANCH AND B.LAYOUT_BRANCH = A.LAYOUT_BRANCH AND B.[ORDER] = 1
   INNER JOIN PP_LINE_AD_EXTEND_DETAIL_JOB_1DAY_TB AS E WITH(NOLOCK) ON E.LINEADID = A.LINEADID AND E.INPUT_BRANCH = A.INPUT_BRANCH AND E.LAYOUT_BRANCH = A.LAYOUT_BRANCH
   LEFT JOIN PP_LOGO_OPTION_TB AS L WITH(NOLOCK) ON L.LINEADID = A.LINEADID AND L.INPUT_BRANCH = A.INPUT_BRANCH AND L.LAYOUT_BRANCH = A.LAYOUT_BRANCH
   WHERE  A.GOODS_MAIN_POSITION IN (1, 2, 3)
     /* AND A.MOBILE_OPT_CODE IN (3,4,8) --2017.04.27 상품개편으로 호출 변경 */


END

