/*************************************************************************************
 *  단위 업무 명 : 관리자 - 로고관리 이원화
 *  작   성   자 : 김 문 화
 *  작   성   일 : 2013/10/23
 *  수   정   자 : 김선호
 *  수   정   일 : 2021/05/03
 *  설        명 : 키워드 검색상품 리스트 노출
 *  수   정   자 : 방 순 현        
 *  수   정   일 : 2021/10/12 
 *  수 정 내  용 : 로고검수 프로세스 개선
 *  주 의  사 항 :
 *  사 용  소 스 :
 *  사 용  예 제 : EXEC GET_M_LOGO_OPTION_MANAGE_LIST_PROC 1, 20, 'LAYOUT_BRANCH',0,0,'MAIN_LOGO','','','',0,'',''
 EXECUTE GET_M_LOGO_OPTION_MANAGE_LIST_PROC 1, 20, 'LAYOUT_BRANCH', 0, 0, 'MAIN_LOGO', '', '', '', '0', 'E', 80
 EXECUTE GET_M_LOGO_OPTION_MANAGE_LIST_PROC 1, 20, 'LAYOUT_BRANCH', 0, 0, 'MAIN_LOGO', '', '', '', '0', 'N', 80, 1
 EXECUTE GET_M_LOGO_OPTION_MANAGE_LIST_PROC 1, 20, 'LAYOUT_BRANCH', 180, 3, 'MAIN_LOGO', '', '', '', '0', 'N', 80, 1
 EXECUTE GET_M_LOGO_OPTION_MANAGE_LIST_PROC 1, 20, 'LAYOUT_BRANCH', 0, 0, 'MAIN_LOGO', '', '', '', '9', '', 80, 1
 --지역판검수
 EXECUTE GET_M_LOGO_OPTION_MANAGE_LIST_PROC 1, 20, 'INPUT_BRANCH', 80, 0, 'MAIN_LOGO', '', '', '', '9', '', 80, 7

EXECUTE GET_M_LOGO_OPTION_MANAGE_LIST_PROC  1, 20, 'LAYOUT_BRANCH', 0, 0, 'MAIN_LOGO', '', 'LINEADID', '1016789255', '9', 'N', 80, 1, 0

EXECUTE GET_M_LOGO_OPTION_MANAGE_LIST_PROC 1, 20, 'LAYOUT_BRANCH', 0, 113, 'MAIN_LOGO', '', '', '', '9', 'M', 80, 5, 0

EXECUTE GET_M_LOGO_OPTION_MANAGE_LIST_PROC 1, 20, 'LAYOUT_BRANCH', 0, 0, 'MAIN_LOGO', '', 'LINEADID', '4057999', '9', '', 80, 5, 0

EXECUTE GET_M_LOGO_OPTION_MANAGE_LIST_PROC  1, 20, 'LAYOUT_BRANCH', 0, 0, 'MAIN_LOGO', '', '', '', '9', 'N', 80, 1, 0

EXECUTE GET_M_LOGO_OPTION_MANAGE_LIST_PROC  1, 20, 'LAYOUT_BRANCH', 0, 0, 'MAIN_LOGO', '', 'LINEADID', '113002455', '9', 'N', 80, 1, 0

EXECUTE GET_M_LOGO_OPTION_MANAGE_LIST_PROC  1, 20, 'LAYOUT_BRANCH', 0, 0, 'MAIN_LOGO', '', 'LINEADID', '113002759', '9', 'N', 80, 1, 0
EXECUTE GET_M_LOGO_OPTION_MANAGE_LIST_PROC  1, 20, 'LAYOUT_BRANCH', 0, 0, 'MAIN_LOGO', '', 'LINEADID', '113002759', '9', 'E', 80, 3, 0
 *************************************************************************************/
ALTER PROC [dbo].[GET_M_LOGO_OPTION_MANAGE_LIST_PROC]

  @PAGE           INT             = 1
, @PAGESIZE       INT             = 20
, @FIELD_BRANCH   VARCHAR(15)     = 'LAYOUT_BRANCH'
, @BRANCHCODE     TINYINT         = 0
, @OPT_CODE       SMALLINT        = 0
, @FIELD_LOGO     VARCHAR(10)     = 'MAIN_LOGO'
, @LOGO_STATUS    CHAR(1)         = ''
, @FIELD_KEWORD   VARCHAR(15)     = ''
, @KEYWORD        VARCHAR(50)     = ''
, @PUB_CONFIRM    TINYINT         = 0       -- 검수상태 (0:대기, 1:완료, 2:재수정, 3:검수거절, 9:전체)
, @VERSION        CHAR(1)         = ''      -- E: E-Comm, M: 등록대행, N: 신문줄광고
, @MAGBRANCHCODE  TINYINT
, @PAGE_GBN     TINYINT       = 0       -- 1:전국, 7:지역
, @ORDERBY        TINYINT         = 0       -- 0:등록일, 1:상세화면로고(WAIT_LOGO_BYTE) 파일용량
AS

  SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
  SET NOCOUNT ON

  DECLARE @SQL_LIST NVARCHAR(MAX)
  DECLARE @SQL_JOIN NVARCHAR(MAX)
  DECLARE @SQL_WHERE NVARCHAR(MAX)
  DECLARE @SQL_COUNT NVARCHAR(MAX)
  DECLARE @SQL_ORDERBY NVARCHAR(500)
  DECLARE @SQL_MAIN_TABLE VARCHAR(100)

  SET @SQL_LIST = ''
  SET @SQL_JOIN = ''
  SET @SQL_WHERE = ''
  SET @SQL_COUNT = ''
  SET @SQL_ORDERBY = ''


  SET @SQL_MAIN_TABLE = 'PP_AD_TB'

  IF @VERSION = 'E'
    BEGIN
      SET @SQL_JOIN = @SQL_JOIN + ' LEFT JOIN PP_ECOMM_RECCHARGE_TB AS RC WITH(NOLOCK) ON RC.ADID  = MT.LINEADID AND RC.PRODUCT_GBN = 1 '
      SET @SQL_WHERE = ' AND MT.[VERSION] = ''E'' AND MT.END_DT >= CONVERT(VARCHAR(10),GETDATE(),120) AND MT.DELYN = ''N'' AND (RC.PrnAmtOk = 1 OR KW.PRNAMTOK = 1) '  -- 게재 예약 또는 게재중인 광고만 노출
    END
 ELSE IF @VERSION = 'M' OR @VERSION = '' --// 지역판일경우 등록대행광고를 기준으로 하여 쿼리
    BEGIN
      SET @SQL_WHERE = ' AND MT.[VERSION] = ''M'' AND MT.END_DT >= CONVERT(VARCHAR(10),GETDATE(),120) AND MT.DELYN = ''N'' '  -- 게재 예약 또는 게재중인 광고만 노출
    END
  ELSE
    BEGIN
      SET @SQL_MAIN_TABLE = 'PP_LINE_AD_TB'
    END
  SET @SQL_WHERE = @SQL_WHERE +  'and MT.'+@FIELD_BRANCH+' in (SELECT INPUT_BRANCH from CM_ADMIN_BRANCH_MAPPING_TB MB WITH(NOLOCK) WHERE MB.MAG_BRANCH = '+CAST(@MAGBRANCHCODE AS VARCHAR)+'  )'
  -- 조회기준
  IF @FIELD_BRANCH = 'LAYOUT_BRANCH' AND @BRANCHCODE > 0
    BEGIN
      IF ISNULL((SELECT TOP 1 AREA_B FROM CC_BRANCH_AREA_TB WHERE SUB_BRANCHCODE = @BRANCHCODE),'') = ''
        BEGIN
          SET @SQL_JOIN = @SQL_JOIN + ' JOIN PP_LINE_AD_AREA_TB AS PA WITH(NOLOCK) ON PA.LINEADNO = MT.LINEADNO '
          SET @SQL_JOIN = @SQL_JOIN + ' JOIN CC_BRANCH_AREA_TB AS BA WITH(NOLOCK) ON BA.AREA_A = PA.AREA_A '
          IF @BRANCHCODE > 0
            BEGIN
              SET @SQL_WHERE = @SQL_WHERE + ' AND BA.SUB_BRANCHCODE  = '+ CAST(@BRANCHCODE AS VARCHAR) +' '
            END
        END
      ELSE  -- 시/도 + 구/군 매핑 지역
        BEGIN
          SET @SQL_JOIN = @SQL_JOIN + ' JOIN PP_LINE_AD_AREA_TB AS PA WITH(NOLOCK) ON PA.LINEADNO = MT.LINEADNO '
          SET @SQL_JOIN = @SQL_JOIN + ' JOIN CC_BRANCH_AREA_TB AS BA WITH(NOLOCK) ON BA.AREA_A = PA.AREA_A AND BA.AREA_B = PA.AREA_B '
          IF @BRANCHCODE > 0
            BEGIN
              SET @SQL_WHERE = @SQL_WHERE + ' AND BA.SUB_BRANCHCODE  = '+ CAST(@BRANCHCODE AS VARCHAR) +' '
            END
        END
    END
  ELSE IF @FIELD_BRANCH = 'INPUT_BRANCH' AND (@BRANCHCODE <> 80 AND @BRANCHCODE > 0)
    BEGIN
      SET @SQL_WHERE = @SQL_WHERE + ' AND MT.INPUT_BRANCH  = '+ CAST(@BRANCHCODE AS VARCHAR) +' '
    END

 -- 지역판 검수대기
 IF @VERSION <> ''
  BEGIN
   SET @SQL_WHERE = @SQL_WHERE + ' AND OP.OPT_AREA&1 = 1 '
  END
  
  -- 유료상품선택
  IF @OPT_CODE > 0
    BEGIN
   IF @OPT_CODE = '93'
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND OP.MOBILE_OPT_CODE = 3 '
    END
   ELSE IF @OPT_CODE = '94'
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND OP.MOBILE_OPT_CODE = 4 '
    END
   ELSE IF @OPT_CODE = '95'
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND OP.MOBILE_OPT_CODE = 5 '
    END
   ELSE IF @OPT_CODE = '96'
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND OP.MOBILE_OPT_CODE = 6 '
    END
   ELSE IF @OPT_CODE = '92'
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND OP.MOBILE_OPT_CODE = 7 '
    END
      ELSE IF @OPT_CODE = '112'
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND OP.MOBILE_OPT_CODE = 9 '
    END
      ELSE IF @OPT_CODE = '113'
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND OP.MOBILE_OPT_CODE = 10 '
    END
      ELSE IF @OPT_CODE = '114'
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND OP.MOBILE_OPT_CODE = 11 '
    END
      ELSE IF @OPT_CODE = '115'
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND OP.MOBILE_OPT_CODE = 12 '
    END
      ELSE IF @OPT_CODE = '116'
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND OP.MOBILE_OPT_CODE = 13 '
    END
      ELSE IF @OPT_CODE = '117'
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND OP.MOBILE_OPT_CODE = 14 '
    END
      ELSE IF @OPT_CODE = '118'
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND OP.MOBILE_OPT_CODE = 15 '
    END
      ELSE IF @OPT_CODE = '119'
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND OP.MOBILE_OPT_CODE = 16 '
    END
      ELSE IF @OPT_CODE = '14'
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND (OP.OPT_CODE = 14 OR OP.OPT_CODE = 41) '
    END
      ELSE IF @OPT_CODE = '3'
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND (OP.OPT_CODE = 3 OR OP.OPT_CODE = 42) '
    END
   ELSE IF @OPT_CODE = '87'
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND (OP.OPT_CODE = 87 OR EXISTS(SELECT TOP(1) LINEADNO FROM PP_JOB_KEYWORDSEARCH_RELATION_TB WITH(NOLOCK) WHERE LINEADNO = MT.LINEADNO)) '
    END
   ELSE
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE + ' AND OP.OPT_CODE = '+ CAST(@OPT_CODE AS VARCHAR) +' '
    END
    END
  ELSE
    BEGIN
      IF @MAGBRANCHCODE = 80    -- 전체관리자가 조회시
        SET @SQL_WHERE = @SQL_WHERE + ' AND (OP.OPT_CODE IN (1,2,3,6,8,9,14,19,12,29,37,38,41,42,51,52,53,55,56,57,60,61,64,65,66,72,73,74,75,76,77,78,79,87) OR OP.MOBILE_OPT_CODE IN (3,4,5,6,7,9,10,11,12,13,14,15,16) OR KW.LINEADNO IS NOT NULL) '
      ELSE  -- 지역관리자 조회시
    SET @SQL_WHERE = @SQL_WHERE + ' AND OP.OPT_CODE IN (3,6,8,9,12,14,19,41,42) '
    END

  -- 로고등록
  IF LEN(@LOGO_STATUS) > 0
    BEGIN
      IF @LOGO_STATUS = 'Y'
      SET @SQL_WHERE = @SQL_WHERE +' AND LO.' + @FIELD_LOGO + ' <> '''' '
     ELSE
       SET @SQL_WHERE = @SQL_WHERE +' AND (LO.' + @FIELD_LOGO + ' IS NULL OR LO.' + @FIELD_LOGO + ' = '''') '
    END

  -- 키워드
  IF LEN(@KEYWORD) > 0
    BEGIN
      IF @FIELD_KEWORD = 'LINEADID'
        SET @SQL_WHERE = @SQL_WHERE +' AND MT.'+ @FIELD_KEWORD +' = '+ @KEYWORD +' '
   ELSE IF @FIELD_KEWORD = 'MWPLUS_AD_NO'
        SET @SQL_WHERE = @SQL_WHERE +' AND WR.adid_wills = '+ @KEYWORD +' '
   ELSE IF @FIELD_KEWORD = 'FIELD_6'
     SET @SQL_WHERE = @SQL_WHERE +' AND FIELD_6 LIKE ''%' + @KEYWORD +'%'' '
      ELSE IF @FIELD_KEWORD = 'PHONE'
     --SET @SQL_WHERE = @SQL_WHERE +' AND MT.PHONE LIKE ''%' + @KEYWORD +'%'' '
  SET @SQL_WHERE = @SQL_WHERE+ ' AND (CASE WHEN CHARINDEX('','',MT.PHONE) = 0 then replace(MT.PHONE,''-'','''') ELSE CASE WHEN replace(RIGHT(MT.PHONE,CHARINDEX('','',REVERSE(MT.PHONE))-1),''-'','''') = ''' + replace(@KEYWORD,'-','') + ''' THEN replace(RIGHT(MT.PHONE, CHARINDEX('','',REVERSE(MT.PHONE)) - 1),''-'','''') ELSE replace(LEFT(MT.PHONE, CHARINDEX('','',MT.PHONE) - 1),''-'','''') END END) = ''' + replace(@KEYWORD,'-','') + ''' '
   ELSE
        SET @SQL_WHERE = @SQL_WHERE +' AND MT.'+ @FIELD_KEWORD +' = '''+ @KEYWORD +''' '
    END
 
  -- 검수상태
 IF @PUB_CONFIRM = 0      -- 검수대기
  BEGIN
   SET @SQL_WHERE = @SQL_WHERE+ ' AND (LO.PUB_CONFIRM = 0 OR LO.LINEADID IS NULL) AND MT.END_DT >= CONVERT(VARCHAR(10),GETDATE(),120) '
  END
  ELSE IF @PUB_CONFIRM = 1      -- 검수완료
  BEGIN
   SET @SQL_WHERE = @SQL_WHERE+ ' AND LO.PUB_CONFIRM = 1 '
  END
  ELSE IF @PUB_CONFIRM = 2      -- 재수정
  BEGIN
   SET @SQL_WHERE = @SQL_WHERE+ ' AND LO.PUB_CONFIRM = 2 '
  END
 ElSE IF @PUB_CONFIRM = 3   -- 검수거절
  BEGIN
   SET @SQL_WHERE = @SQL_WHERE+ ' AND LO.PUB_CONFIRM = 3 '
  END
 ElSE IF @PUB_CONFIRM = 9   -- 전체
  BEGIN
   IF @PAGE_GBN = 1 OR @PAGE_GBN = 3 OR @PAGE_GBN = 5 OR @PAGE_GBN = 7
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE+ ' AND (LO.PUB_CONFIRM IN (0, 2) OR LO.LINEADID IS NULL) '
    END
   ELSE
    BEGIN
     SET @SQL_WHERE = @SQL_WHERE+ ' AND LO.PUB_CONFIRM IN (1, 3) '
    END

      SET @SQL_WHERE = @SQL_WHERE+ ' AND MT.END_DT >= CONVERT(VARCHAR(10),GETDATE(),120) '
  END
  ELSE
  BEGIN
   SET @SQL_WHERE = @SQL_WHERE+ ' AND (LO.PUB_CONFIRM IN (0, 2) OR LO.LINEADID IS NULL) '
  END


  --정렬
  IF @ORDERBY = 0 OR @ORDERBY IS NULL OR @ORDERBY = ''
    SET @SQL_ORDERBY = 'ORDER BY AA.LOGO_REG_DT DESC, AA.REG_DT DESC'
  ELSE IF @ORDERBY = 1
    SET @SQL_ORDERBY = 'ORDER BY AA.WAIT_LOGO_BYTE DESC, AA.REG_DT DESC'

  SET @SQL_COUNT = 'SELECT COUNT(*) AS CNT
  FROM (SELECT MT.LINEADID, MT.INPUT_BRANCH, MT.LAYOUT_BRANCH
          FROM '+ @SQL_MAIN_TABLE +' AS MT WITH(NOLOCK) '+ @SQL_JOIN +'
        JOIN PP_OPTION_TB AS OP WITH(NOLOCK) ON OP.LINEADNO = MT.LINEADNO
  LEFT JOIN PP_LOGO_OPTION_TB AS LO WITH(NOLOCK) ON LO.LINEADNO = MT.LINEADNO
  LEFT JOIN PP_AD_WILLS_RELATION_TB AS WR WITH(NOLOCK) ON WR.LINEADNO = MT.LINEADNO
  LEFT JOIN V_PP_JOB_KEYWORDSEARCH_PAY AS KW WITH(NOLOCK) ON KW.LINEADNO = MT.LINEADNO
  WHERE MT.GROUP_CD = 14
    --AND MT.INPUT_BRANCH <> 181
    AND OP.OPT_END_DT >= CONVERT(VARCHAR(10), GETDATE(), 120)
    '+ @SQL_WHERE +'
  GROUP BY MT.LINEADID, MT.INPUT_BRANCH, MT.LAYOUT_BRANCH) AS A OPTION(MAXDOP 1)'




  SET @SQL_LIST = 'SELECT
   B.LINEADID
  ,B.INPUT_BRANCH
  ,B.LAYOUT_BRANCH
  ,REPLACE(REPLACE(ISNULL(C.WAIT_COMPANY , B.FIELD_6),''<'',''&lt;''),''>'',''&gt;'') AS COMPANY
  ,ISNULL(C.WAIT_TITLE , B.TITLE) AS TITLE
  ,C.MAIN_TITLE
  ,ISNULL(C.PUB_LOGO,'''') PUB_LOGO
  ,C.WAIT_LOGO
  ,C.IMPACT_LOGO
  ,B.REG_DT
  ,OP.OPT_START_DT
  ,OP.OPT_END_DT
  ,C.PUB_CONFIRM
  ,CASE WHEN ISNULL(C.MAIN_LOGO,'''') ='''' THEN ISNULL(C.PUB_LOGO , '''') ELSE C.MAIN_LOGO END AS MAIN_LOGO'

 IF @VERSION = 'E'
  SET @SQL_LIST = @SQL_LIST + ', ''E'' AS [VERSION] '
 ELSE IF @VERSION = 'M'
  SET @SQL_LIST = @SQL_LIST + ', ''M'' AS [VERSION] '
 ELSE
  SET @SQL_LIST = @SQL_LIST + ', B.[VERSION] '

  SET @SQL_LIST = @SQL_LIST + '
  ,B.FINDCODE
  ,OP.OPT_CODE
  ,OP.MOBILE_OPT_CODE
  ,OP.DISPLAY_OPT
  ,ISNULL(C.WAIT_LOGO_BYTE, 0) AS WAIT_LOGO_BYTE
  ,CASE WHEN ISNULL(C.MAIN_LOGO_BYTE, 0)=0 THEN C.PUB_LOGO_BYTE ELSE C.MAIN_LOGO_BYTE END AS MAIN_LOGO_BYTE
  ,C.LOGO_TEMPLATE
  ,C.LOGO_CONFIRM
  ,C.LOGO_CONFIRM_IMG
  ,C.LOGO_CONFIRM_URL
  ,C.PUB_CONFIRM_COMMENT
  ,C.PUB_CONFIRM_DT
  ,WR.adid_wills AS MWPLUS_AD_NO
  ,ISNULL((SELECT TOP(1) K.KEYWORDSEARCHADID FROM PP_JOB_KEYWORDSEARCH_RELATION_TB AS K WITH(NOLOCK) WHERE K.LINEADNO = B.LINEADNO ORDER BY K.KEYWORDSEARCHADID DESC), 0) AS KEYWORDSEARCHADID --키워드 검색상품 번호
  FROM (SELECT ROW_NUMBER() OVER (' + @SQL_ORDERBY + ') AS ROWNUM,*
        FROM (SELECT MT.LINEADID, MT.INPUT_BRANCH, MT.LAYOUT_BRANCH, MT.REG_DT, LO.REG_DT AS LOGO_REG_DT, ISNULL(LO.WAIT_LOGO_BYTE, 0) AS WAIT_LOGO_BYTE
  FROM '+ @SQL_MAIN_TABLE +' AS MT WITH(NOLOCK) '+ @SQL_JOIN +'
  JOIN PP_OPTION_TB AS OP WITH(NOLOCK) ON OP.LINEADNO = MT.LINEADNO
  LEFT JOIN PP_LOGO_OPTION_TB AS LO WITH(NOLOCK) ON LO.LINEADNO = MT.LINEADNO
  LEFT JOIN PP_AD_WILLS_RELATION_TB AS WR WITH(NOLOCK) ON WR.LINEADNO = MT.LINEADNO
  LEFT JOIN V_PP_JOB_KEYWORDSEARCH_PAY AS KW WITH(NOLOCK) ON KW.LINEADNO = MT.LINEADNO
  WHERE MT.GROUP_CD = 14
  --AND MT.INPUT_BRANCH <> 181
  AND OP.OPT_END_DT >= CONVERT(VARCHAR(10), GETDATE(), 120)
  '+ @SQL_WHERE +' 
  GROUP BY MT.LINEADID, MT.INPUT_BRANCH, MT.LAYOUT_BRANCH, MT.REG_DT, LO.REG_DT, LO.WAIT_LOGO_BYTE
    ) AS AA
  ) AS A
  JOIN '+ @SQL_MAIN_TABLE +' AS B WITH(NOLOCK) ON B.LINEADID = A.LINEADID AND B.INPUT_BRANCH = A.INPUT_BRANCH AND B.LAYOUT_BRANCH = A.LAYOUT_BRANCH
  JOIN PP_OPTION_TB AS OP WITH(NOLOCK) ON OP.LINEADID = A.LINEADID AND OP.INPUT_BRANCH = A.INPUT_BRANCH AND OP.LAYOUT_BRANCH = A.LAYOUT_BRANCH
  LEFT JOIN PP_LOGO_OPTION_TB AS C WITH(NOLOCK) ON C.LINEADID = A.LINEADID AND C.INPUT_BRANCH = A.INPUT_BRANCH AND C.LAYOUT_BRANCH = A.LAYOUT_BRANCH
  LEFT OUTER JOIN PP_AD_WILLS_RELATION_TB AS WR WITH(NOLOCK) ON WR.LINEADNO = B.LINEADNO
  WHERE A.ROWNUM>' + CONVERT(VARCHAR,(@PAGE-1) * @PAGESIZE) + '
    AND A.ROWNUM<=' + CONVERT(VARCHAR,(@PAGE) * @PAGESIZE) + '
  ORDER BY A.ROWNUM  OPTION(MAXDOP 1)'

  --PRINT @SQL_COUNT
  PRINT @SQL_LIST
  PRINT CAST(@SQL_LIST AS TEXT)  

  EXECUTE SP_EXECUTESQL @SQL_COUNT
  EXECUTE SP_EXECUTESQL @SQL_LIST




 
