


/*************************************************************************************
 *  단위 업무 명 : 구인관리자 > 인터넷 등록 구인줄광고 > 등록내역 리스트
 *  작   성   자 : 최 병찬
 *  작   성   일 : 2013/07/17
 *  수   정   자 : 정헌수
 *  수   정   일 : 2016-01-06
 *  설        명 : @strSQLINDEX (full scan 시 인덱스 사용 안되게 (PK 사용하게)변경
 *  수   정   자 : 방 순 현        
 *  수   정   일 : 2021/10/12 
 *  수 정 내  용 : 로고검수 프로세스 개선
 *  주 의  사 항 :
 *  사 용  소 스 : 등록대행 구인광고 리스트
 *  사 용  예 제 :
EXECUTE DBO.GET_M_ONLINE_LINEAD_JOB_LIST_PROC_BK01 '', '', '', '', '', '', '', 'INPUT_BRANCH', '', '', '', '', '', '1', '20', '', '', 80,'N','Y'
EXECUTE DBO.GET_M_ONLINE_LINEAD_JOB_LIST_PROC '', '', '', '', '', '0', '1013596046', 'INPUT_BRANCH', '', '', '', '', '', '1', '100000', '', '', 80
EXECUTE DBO.GET_M_ONLINE_LINEAD_JOB_LIST_PROC '', '', '', '', '', '3', '010-3811-4464', 'INPUT_BRANCH', '', '', '', '', '', '1', '20', '', '', 80
EXECUTE DBO.GET_M_ONLINE_LINEAD_JOB_LIST_PROC_BK01 '', '', '', '', '', '3', '010-3811-4464', 'INPUT_BRANCH', '', '', '', '', '', '1', '20', '', '', 80
EXECUTE DBO.GET_M_ONLINE_LINEAD_JOB_LIST_PROC_BK01 '', '', '', '', '', '3', '', 'INPUT_BRANCH', '', '', '1', '', '', '1', '20', '', '', 80, 'N', ''
EXECUTE DBO.GET_M_ONLINE_LINEAD_JOB_LIST_PROC_BK01 '', '', '', '', '', '', '', 'INPUT_BRANCH', '', '', '', '', '', '1', '20', '', '', 80, 'N', ''
EXECUTE DBO.GET_M_ONLINE_LINEAD_JOB_LIST_PROC '', '', '', '', '', '', '', 'INPUT_BRANCH', '', '', '', '', '', '1', '20', '', '', 80, 'N', ''
EXECUTE DBO.GET_M_ONLINE_LINEAD_JOB_LIST_PROC_BK01 '', '', '', '', '', '3', '', 'INPUT_BRANCH', '', '', '6', '', '', '1', '20', '', '', 80, 'N', ''
EXECUTE DBO.GET_M_ONLINE_LINEAD_JOB_LIST_PROC '', '', '', '', '', '3', '', 'INPUT_BRANCH', '', '', '6', '', '', '1', '20', '', '', 80, 'N', ''

EXECUTE DBO.GET_M_ONLINE_LINEAD_JOB_LIST_PROC '', '1', '', '', '', '3', '', 'INPUT_BRANCH', '8', '', '', '', '', '1', '20', '2', '', 80, 'N', ''


EXECUTE DBO.GET_M_ONLINE_LINEAD_JOB_LIST_PROC '', '', '', '', '', '', '', 'INPUT_BRANCH', '', '', '', '', '', '1', '20', '', '', 80, 'N', '', NULL

EXECUTE DBO.GET_M_ONLINE_LINEAD_JOB_LIST_PROC '', '', '', '', '', '3', '', 'INPUT_BRANCH', '', '', '', '', '', '1', '20', '', '', 80, 'N', '', 1
EXECUTE DBO.GET_M_ONLINE_LINEAD_JOB_LIST_SPOT_PROC '', '', '', '', '', '0', '1016137696', 'INPUT_BRANCH', '', '', '2', '', '', '1', '100000', '', '', 80, 'Y' 
 *************************************************************************************/
ALTER PROCEDURE [dbo].[GET_M_ONLINE_LINEAD_JOB_LIST_SPOT_PROC]
(
      @BRANCH         VARCHAR(3)   = ''    -- COMBO값
,     @strHTMLFLAG    CHAR(1)   = ''
,     @strDTDIV       CHAR(1)    = ''
,     @strStDate      VARCHAR(10)   = ''
,     @strEnDate      VARCHAR(10)   = ''
,     @strKey         CHAR(1)    = ''
,     @strWord        VARCHAR(100)  = ''
,     @BRANCH_FIELD   VARCHAR(13)
,     @OPT_CODE       VARCHAR(5)
,     @OPT_AREA       CHAR(1)
,     @STATUS         CHAR(1) = ''
,     @CONFIRM        CHAR(1) = ''
,     @OPT_PATH       CHAR(1) = ''  -- 1:인터넷상품등록, 2:신문우대등록, 0:우대일반
,     @n4Page         INT
,     @n2PageSize     INT
,     @OPT_STATUS     CHAR(1) = ''
,     @BRANCH_LOCAL   TINYINT = 0    -- 지점소재지역
,     @MAG_BRANCH     TINYINT          -- MAGBRANCH(쿠키값)
,     @EXCEL_YN       CHAR(1) = 'N'
,     @chkHOLDOFF     VARCHAR(1)='N'
,     @UPRIGHT_AGREE  TINYINT = 0
)
AS
  SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
  SET NOCOUNT ON

  DECLARE @strSQL    NVARCHAR(MAX)
  DECLARE @strSQLSUB  NVARCHAR(MAX)
  DECLARE @strSQLSUB2  NVARCHAR(MAX)
  DECLARE @strSQLSUB3   NVARCHAR(MAX)
  DECLARE @strSQLJOIN   NVARCHAR(MAX)
  DECLARE @strSQLFIELD  NVARCHAR(MAX)
  --DECLARE @strSQLINDEX  NVARCHAR(100)
  DECLARE @TODAY    VARCHAR(19)

  DECLARE @SQL_PARAM nvarchar(max)

  SET @SQL_PARAM ='      @BRANCH         VARCHAR(3)
,     @strHTMLFLAG    CHAR(1)
,     @strDTDIV       CHAR(1)
,     @strStDate      VARCHAR(10)
,     @strEnDate      VARCHAR(10)
,     @strKey         CHAR(1)
,     @strWord        VARCHAR(100)
,     @BRANCH_FIELD   VARCHAR(13)
,     @OPT_CODE       VARCHAR(5)
,     @OPT_AREA       CHAR(1)
,     @STATUS         CHAR(1)
,     @CONFIRM        CHAR(1)
,     @OPT_PATH       CHAR(1)
,     @n4Page         INT
,     @n2PageSize     INT
,     @OPT_STATUS     CHAR(1)
,     @BRANCH_LOCAL   TINYINT
,     @MAG_BRANCH     TINYINT
,     @EXCEL_YN       CHAR(1)
,     @chkHOLDOFF     VARCHAR(1)
'
  SET @TODAY = CONVERT(VARCHAR(10),GETDATE(),120)

  SET @strSQLSUB = ''
  SET @strSQL = ''
  SET @strSQLJOIN = ''
  SET @strSQLSUB3 = ''
  SET @strSQLFIELD = ''
  --SET @strSQLINDEX = ''

  SET @strSQLJOIN = ' LEFT JOIN PP_AD_HOLDOFF_TB HOLD WITH(NOLOCK) ON HOLD.LINEADNO = C.LINEADNO '

  -- 지점지역 검색
  IF @BRANCH_LOCAL > 0
    BEGIN
      SET @strSQLSUB = @strSQLSUB + ' AND BM.LOCALSITE = @BRANCH_LOCAL '
    END
  IF @chkHOLDOFF = 'Y'
  BEGIN
    SET @strSQLSUB = @strSQLSUB+ ' AND HOLD.SEQ IS NOT NULL '
  END

  -- 지점 검색
  IF @BRANCH > 10
    BEGIN
      IF @BRANCH = 90
        SET @strSQLSUB = @strSQLSUB + ' AND C.'+ @BRANCH_FIELD +' IN (16,17,22,18,21,19,23,20,24,90) '
      ELSE IF @BRANCH = 201
        SET @strSQLSUB = @strSQLSUB + ' AND C.'+ @BRANCH_FIELD +' IN (16,17,201) '
      ELSE IF @BRANCH = 202
        SET @strSQLSUB = @strSQLSUB + ' AND C.'+ @BRANCH_FIELD +' IN (20,22,202) '
      ELSE IF @BRANCH = 203
        SET @strSQLSUB = @strSQLSUB + ' AND C.'+ @BRANCH_FIELD +' IN (19,23,203) '
      ELSE IF @BRANCH = 204
        SET @strSQLSUB = @strSQLSUB + ' AND C.'+ @BRANCH_FIELD +' IN (18,21,24,204) '
      ELSE IF @BRANCH = 83
        SET @strSQLSUB = @strSQLSUB + ' AND C.'+ @BRANCH_FIELD +' IN (11,26,39,41,60,83) '
      ELSE IF @BRANCH = 94
        SET @strSQLSUB = @strSQLSUB + ' AND C.'+ @BRANCH_FIELD +' IN (25,49,34,35,48,46,47,94) '
      ELSE IF @BRANCH = 80
        SET @strSQLSUB = @strSQLSUB + ' '
      ELSE
        SET @strSQLSUB = @strSQLSUB + ' AND C.'+ @BRANCH_FIELD +' = '+ CAST(@BRANCH AS VARCHAR(3))
    END
  ELSE
    BEGIN
      IF @BRANCH = 1
        SET @strSQLSUB = @strSQLSUB + ' AND C.'+ @BRANCH_FIELD +' IN (16,17,22,18,21,19,23,20,24,87,90,92,201,202,203,204) '
      ELSE IF @BRANCH = 2
        SET @strSQLSUB = @strSQLSUB + ' AND C.'+ @BRANCH_FIELD +' IN (36,28,10,29,14,30,31,32,43,27,33) '
      ELSE IF @BRANCH = 3
        SET @strSQLSUB = @strSQLSUB + ' AND C.'+ @BRANCH_FIELD +' IN (11,25,49,26,41,39,34,35,60,48,46,47) '
      ELSE IF @BRANCH = 4
        SET @strSQLSUB = @strSQLSUB + ' AND C.'+ @BRANCH_FIELD +' IN (12,54,42,53,40,55) '
      ELSE IF @BRANCH = 5
        SET @strSQLSUB = @strSQLSUB + ' AND C.'+ @BRANCH_FIELD +' IN (15,13,58,50) '
      ELSE IF @BRANCH = 6
        SET @strSQLSUB = @strSQLSUB + ' AND C.'+ @BRANCH_FIELD +' IN (52,56,38,37) '
      ELSE IF @BRANCH = 7
        SET @strSQLSUB = @strSQLSUB + ' AND C.'+ @BRANCH_FIELD +' = 110 '
      ELSE IF @BRANCH = 0
        SET @strSQLSUB = @strSQLSUB + ''
      ELSE
        SET @strSQLSUB = @strSQLSUB + ' AND C.'+ @BRANCH_FIELD +' = '+ CAST(@BRANCH AS VARCHAR(3))
    END

  -- 날짜상태
  IF @strDTDIV <> '' BEGIN
    IF @strDTDIV = '0' BEGIN
      SET @strSQLSUB = @strSQLSUB+ ' AND (C.REG_DT >= CONVERT(DATETIME, ''' + @strStDate + ''') AND C.REG_DT <= CONVERT(DATETIME, ''' + @strEnDate + ' 23:59:59''))'
    END ELSE IF @strDTDIV = '1' BEGIN
      SET @strSQLSUB = @strSQLSUB+ ' AND (C.START_DT >= CONVERT(DATETIME, ''' + @strStDate + ''') AND C.START_DT <= CONVERT(DATETIME, ''' + @strEnDate + ' 23:59:59''))'
    END ELSE IF @strDTDIV = '2' BEGIN
      SET @strSQLSUB = @strSQLSUB+ ' AND (C.END_DT >= CONVERT(DATETIME, ''' + @strStDate + ''') AND C.END_DT <= CONVERT(DATETIME, ''' + @strEnDate + ' 23:59:59''))'
    END
  END

  -- HTML여부 (엑셀 출력에서만 사용)
  IF @strHTMLFLAG <> ''
    BEGIN
      SET @strSQLFIELD = ' , ED.HTML_FLAG '
      SET @strSQLJOIN = @strSQLJOIN + ' LEFT JOIN PP_LINE_AD_EXTEND_DETAIL_TB AS ED (NOLOCK) ON ED.LINEADNO = C.LINEADNO '
      SET @strSQLSUB3 = @strSQLSUB3 + ' AND ED.HTML_FLAG = ''' + @strHTMLFLAG + ''' '
    END
  Else
    BEGIN
      SET @strSQLFIELD = ' , NULL AS HTML_FLAG '
    END

  IF @EXCEL_YN = 'Y'
    BEGIN
      SET @strSQLFIELD += ' , ISNULL(AC.APP_ONLINE_CNT, 0) AS APP_ONLINE_CNT, ISNULL(AC.APP_EMAIL_CNT, 0) AS APP_EMAIL_CNT, ISNULL(AC.APP_SMS_CNT, 0) AS APP_SMS_CNT, CASE WHEN WR.LINEADNO IS NULL THEN 0 ELSE ISNULL(WR.adid_wills,0) END AS MWPLUS_AD_NO, SERVICE_APPROVAL, SERVICE_REASON, CUSTOMER_CD, MINUS_POINT, DISCOUNT_PRICE, DISCOUNT_REASON, OS.SERVICEF, OS.REG_KIND '
      --SET @strSQLJOIN += ' LEFT JOIN PP_LINE_AD_APP_TYPE_CNT_TB (NOLOCK) AC ON AC.LINEADNO = C.LINEADNO '
      --SET @strSQLJOIN += ' LEFT JOIN PP_OPTION_PATH_SUB_DATA_TB (NOLOCK) OS ON OS.LINEADNO = P.LINEADNO '
      SET @strSQLJOIN += ' LEFT JOIN PP_JOB_PROMOTION_LOG_VI AS PM ON PM.ADID = C.LINEADNO '
    END
  ELSE
    BEGIN
      SET @strSQLFIELD += ' , 0 AS APP_ONLINE_CNT, 0 AS APP_EMAIL_CNT, 0 AS APP_SMS_CNT, CASE WHEN WR.LINEADNO IS NULL THEN 0 ELSE ISNULL(WR.adid_wills,0) END AS MWPLUS_AD_NO, '''' AS SERVICE_APPROVAL, '''' AS SERVICE_REASON, '''' AS CUSTOMER_CD, '''' AS MINUS_POINT, '''' AS DISCOUNT_PRICE, '''' AS DISCOUNT_REASON '
    END

  --// 추가되는 기본 JOIN 테이블은 이곳에 추가할 것
  SET @strSQLJOIN += ' LEFT JOIN PP_LINE_AD_APP_TYPE_CNT_TB (NOLOCK) AC ON AC.LINEADNO = C.LINEADNO '
  SET @strSQLJOIN += ' LEFT JOIN PP_OPTION_PATH_SUB_DATA_TB (NOLOCK) OS ON OS.LINEADNO = P.LINEADNO '

  --// 추가되는 필드는 이곳에 추가할 것
  SET @strSQLFIELD += ' , 0 AS CNT_W, 0 AS CNT_MW, 0 AS CNT_MA_ANDROID, 0 AS CNT_MA_IPHONE 
  , ISNULL(PR.RESERVE_START_DT, C.START_DT) AS ADSTART_DT
  , ISNULL(PR.RESERVE_END_DT, C.END_DT) AS ADEND_DT
  , C.ENDYN
  , C.LINEADNO
  , CASE WHEN HOLD.STAT IS NOT NULL THEN ''보류'' ELSE '''' END
    + CASE WHEN HOLD.STAT = 0 THEN ''(잔여일 '' + CAST(HOLD.REMAINCOUNT AS VARCHAR) +''일)'' ELSE '''' END AS HOLDSTR
  ,  ISNULL(HOLD.SEQ,0) AS HOLDSEQ
  , PR.RESERVE_START_DT
  , PR.RESERVE_END_DT
  , C.CUID
  , DJ.UPRIGHT_AGREE
  , C.ISSTORAGE
  , CASE WHEN WR.LINEADNO IS NULL THEN -1
                                  ELSE ISNULL(WR.adid_wills,0)
                                  END
    AS WILLS_ADID
  ,ISNULL(CT.HIT_CNT_PC,0) AS HIT_CNT_PC
  ,ISNULL(CT.HIT_CNT_MO,0) AS HIT_CNT_MO
  ,ISNULL(CT.APP_CNT_PC,0) AS APP_CNT_PC
  ,ISNULL(CT.APP_CNT_MO,0) AS APP_CNT_MO
  ,SN.S_OPT_NAME
  ,OS.ORG_AMOUNT
  ,OS.MAG_NAME
  ,C.AREA_A
  ,C.AREA_B
  ,CD.HEADCODEFULLNM 
  ,WR.CUSTCODE AS W_CUSTCODE
  ,OS.AREA_GROUP
  ,STUFF((SELECT '','' + LTRIM(RTRIM(KEYWORD)) FROM PP_JOB_KEYWORDSEARCH_TB  WITH(NOLOCK) where KEYWORDSEARCHADID IN (SELECT KEYWORDSEARCHADID FROM PP_JOB_KEYWORDSEARCH_RELATION_TB WHERE LINEADNO=C.LINEADNO) FOR XML PATH('''')), 1,1,'''') AS KEYWORD_LIST  
  ,STUFF((SELECT '','' + LTRIM(RTRIM(PERIOD)) FROM PP_JOB_KEYWORDSEARCH_TB  WITH(NOLOCK) where KEYWORDSEARCHADID IN (SELECT KEYWORDSEARCHADID FROM PP_JOB_KEYWORDSEARCH_RELATION_TB WHERE LINEADNO=C.LINEADNO) FOR XML PATH('''')), 1,1,'''') AS PERIOD_LIST  
  ,STUFF((SELECT '','' + CONVERT(CHAR(10),START_DT,23) FROM PP_JOB_KEYWORDSEARCH_TB  WITH(NOLOCK) where KEYWORDSEARCHADID IN (SELECT KEYWORDSEARCHADID FROM PP_JOB_KEYWORDSEARCH_RELATION_TB WHERE LINEADNO=C.LINEADNO) FOR XML PATH('''')), 1,1,'''') AS STARTDT_LIST  
  ,STUFF((SELECT '','' + CONVERT(CHAR(10),END_DT,23) FROM PP_JOB_KEYWORDSEARCH_TB  WITH(NOLOCK) where KEYWORDSEARCHADID IN (SELECT KEYWORDSEARCHADID FROM PP_JOB_KEYWORDSEARCH_RELATION_TB WHERE LINEADNO=C.LINEADNO) FOR XML PATH('''')), 1,1,'''') AS ENDDT_LIST '

  IF @EXCEL_YN = 'Y'
    BEGIN
      SET @strSQLFIELD += ',PM.PROMOTION_NAME '
    END

  -- 게재상태
  IF @STATUS = 1 -- 게재전
    --SET @strSQLSUB = @strSQLSUB + ' AND ( CONVERT(VARCHAR(10),C.END_DT,120) >= CONVERT(VARCHAR(10),GETDATE(),120) AND PP.LINEADID IS NULL AND C.DELYN = ''N'') '
    SET @strSQLSUB = @strSQLSUB + ' AND ((FC.STATUS = 1 AND C.START_DT > CONVERT(VARCHAR(10),GETDATE(),120)) OR (FC.STATUS IS NULL AND C.START_DT > CONVERT(VARCHAR(10),GETDATE(),120))  AND (C.DELYN = ''N'' AND C.ENDYN = ''N'')) '
  ELSE IF @STATUS = 2 -- 게재중
    --SET @strSQLSUB = @strSQLSUB + ' AND ( PP.LINEADID IS NOT NULL AND C.DELYN = ''N'') '
    SET @strSQLSUB = @strSQLSUB + ' AND ( PP.LINEADID IS NOT NULL AND (C.DELYN = ''N'' OR C.ENDYN = ''N'')) '
  ELSE IF @STATUS = 3 -- 게재종료
    --SET @strSQLSUB = @strSQLSUB + ' AND ( CONVERT(VARCHAR(10),C.END_DT,120) < CONVERT(VARCHAR(10),GETDATE120) OR C.DELYN = ''Y'') '
    SET @strSQLSUB = @strSQLSUB + ' AND (C.END_DT < CONVERT(VARCHAR(10),GETDATE(),120) OR (C.DELYN = ''Y'' OR C.ENDYN = ''Y'')) '
  ELSE IF @STATUS = 4 -- 강제마감
    SET @strSQLSUB = @strSQLSUB + ' AND C.ENDYN = ''Y'' '
  ELSE IF @STATUS = 5 -- 삭제
    SET @strSQLSUB = @strSQLSUB + ' AND C.DELYN = ''Y'' '
  ELSE IF @STATUS = 6 -- 게재전(예약)
    SET @strSQLSUB = @strSQLSUB + ' AND PR.RESERVE_START_DT > GETDATE() '

  -- 무료광고 심사
  IF @CONFIRM = '0' OR @CONFIRM='1'
  BEGIN
    SET @strSQLSUB = @strSQLSUB+ ' AND FC.STATUS = @CONFIRM '
  END
  ELSE IF @CONFIRM='2'
  BEGIN
    SET @strSQLSUB = @strSQLSUB+ ' AND FC.STATUS NOT IN (0,1)'
  END

  -- 등록구분
  IF @OPT_PATH <> ''
    SET @strSQLSUB = @strSQLSUB + ' AND P.OPT_PATH = @OPT_PATH '

  -- 인터넷옵션 (옵션) & 일반리스트 노출 옵션 동시 조건 검색
  IF @OPT_CODE <> ''
    BEGIN
      IF @OPT_CODE ='0'   --무료광고
        BEGIN
          SET @strSQLSUB = @strSQLSUB + ' AND FC.STATUS IS NOT NULL '
          IF @OPT_AREA<>''
          BEGIN
            SET @strSQLSUB = @strSQLSUB + ' AND P.OPT_AREA&'+ @OPT_AREA +' = '+ @OPT_AREA +' '
          END
        END
      ELSE
        SET @strSQLSUB = @strSQLSUB + ' AND S.S_OPTCODE = '+ @OPT_CODE +' '
    END

  -- 옵션 게재상태
  IF @OPT_STATUS = '1'  -- 게재전
    SET @strSQLSUB = @strSQLSUB + ' AND (P.OPT_CODE > 0 OR P.MOBILE_OPT_CODE > 0) AND P.OPT_START_DT > CONVERT(VARCHAR(10),GETDATE(),120) '
  ELSE IF @OPT_STATUS = '2' -- 게재중
    SET @strSQLSUB = @strSQLSUB + ' AND (P.OPT_CODE > 0 OR P.MOBILE_OPT_CODE > 0) AND (P.OPT_START_DT <= CONVERT(VARCHAR(10),GETDATE(),120) AND P.OPT_END_DT >= CONVERT(VARCHAR(10),GETDATE(),120)) AND PP.LINEADID IS NOT NULL'
  ELSE IF @OPT_STATUS = '3' -- 게재종료
    SET @strSQLSUB = @strSQLSUB + ' AND (P.OPT_CODE > 0 OR P.MOBILE_OPT_CODE > 0) AND P.OPT_END_DT < CONVERT(VARCHAR(10),GETDATE(),120) '

  -- 키워드
  IF @strWord <> ''
  BEGIN
    --IF @strKey = '' BEGIN
    --   SET @strSQLSUB = @strSQLSUB+' AND (C.LINEADID = '''+@strWord+''' OR C.LINEADNO = '''+@strWord+''' OR C.USER_ID LIKE ''%' + @strWord + '%'' OR C.PHONE LIKE ''%' + @strWord + '%'' OR R.RecNm LIKE ''%'+@strWord+'%'')'
    --END ELSE 
    IF  @strKey = '0' BEGIN  -- 광고번호
      IF LEN(@strWord) = 16  --// 2015.05.28 접수번호일때는 LINEADID OR LINEADNO 모두 검색으로 변경
        BEGIN
          SET @strSQLSUB = @strSQLSUB+' AND C.LINEADNO = @strWord '
        END
      ELSE
        BEGIN
          SET @strSQLSUB = @strSQLSUB+' AND C.LINEADID = @strWord '
        END
    END ELSE IF  @strKey = '1' BEGIN -- 아이디
    SET @strSQLSUB = @strSQLSUB+' AND C.USER_ID = '''+@strWord+'''  '
    END ELSE IF  @strKey = '2' BEGIN -- 담당자명
       SET @strSQLSUB = @strSQLSUB+' AND OS.MAG_NAME = '''+@strWord+'''  '
    END ELSE IF  @strKey = '3' BEGIN -- 전화번호
      --IF LEN(@strWord) >=10 BEGIN
      --  SET @strSQLSUB = @strSQLSUB + ' AND C.LINEADNO IN (SELECT LINEADNO FROM PP_AD_PHONE_TB  WITH(NOLOCK) where S_PHONE = ''' + replace(@strWord ,'-','') +''') '
      --      END
      --ELSE BEGIN
      --  SET @strSQLSUB = @strSQLSUB+' AND C.PHONE LIKE ''%'+@strWord+'%''  '
      --      END
   IF LEN(@strWord) >=10 
  BEGIN
           SET @strSQLSUB = @strSQLSUB + ' AND C.LINEADNO IN (SELECT LINEADNO FROM PP_AD_PHONE_TB WITH(NOLOCK)  where S_PHONE = ''' + replace(@strWord ,'-','') +''') ' 
  END
      ELSE BEGIN
        SET @strSQLSUB = @strSQLSUB+' AND (CASE WHEN CHARINDEX('','',C.PHONE) = 0 THEN C.PHONE  ELSE CASE WHEN  RIGHT(C.PHONE,CHARINDEX('','',REVERSE(C.PHONE))-1) = ''' + @strWord + ''' THEN dbo.FN_SPLIT(C.PHONE,'','',2) ELSE  dbo.FN_SPLIT(C.PHONE,'','',1) END END = ''' + @strWord +''')'  
      END  
    END ELSE IF  @strKey = '4' BEGIN -- 광고주명
      SET @strSQLSUB = @strSQLSUB+' AND C.ORDER_NAME LIKE ''%'+@strWord+'%''  '
    END ELSE IF  @strKey = '5' BEGIN -- 상호
      SET @strSQLSUB = @strSQLSUB +' AND C.FIELD_6 LIKE ''%'+ @strWord +'%'' '
    END ELSE IF  @strKey = '6' BEGIN -- 제목
      SET @strSQLSUB = @strSQLSUB +' AND C.TITLE LIKE ''%'+ @strWord +'%'' '
    END ELSE IF  @strKey = '7' BEGIN -- 윌리언트공고번호검색
   SET @strSQLSUB = @strSQLSUB +' AND WR.adid_wills = @strWord '
    END
  END

  IF @UPRIGHT_AGREE IS NOT NULL OR @UPRIGHT_AGREE <> ''
  BEGIN
    SET @strSQLSUB += ' AND DJ.UPRIGHT_AGREE = ' + CAST(@UPRIGHT_AGREE AS VARCHAR)
  END


  SET @strSQL='SELECT COUNT(C.LINEADID) AS CNT
    FROM PP_AD_TB C WITH(NOLOCK)
  JOIN CM_ADMIN_BRANCH_MAPPING_TB AS BM WITH(NOLOCK) ON BM.'+ @BRANCH_FIELD +' = C.'+ @BRANCH_FIELD +'
  JOIN PP_SPOT_AD_JOB_TB AS S WITH(NOLOCK) ON S.LINEADNO = C.LINEADNO
  JOIN PP_FINDCODE_TB AS CD WITH(NOLOCK) ON CD.CODE4 = C.FINDCODE
  LEFT JOIN PP_OPTION_TB P (NOLOCK) ON C.LINEADNO = P.LINEADNO
  LEFT JOIN PP_LINE_AD_EXTEND_DETAIL_JOB_TB DJ (NOLOCK) ON C.LINEADNO = DJ.LINEADNO
  LEFT JOIN PP_LINE_AD_TB AS PP (NOLOCK) ON PP.LINEADNO = C.LINEADNO
  LEFT JOIN PP_FREE_AD_CONFIRM_TB AS FC (NOLOCK) ON FC.LINEADNO = C.LINEADNO
  LEFT JOIN MWDB.dbo.CommonMagUser AS E WITH(NOLOCK) ON E.MAGID = C.MAG_ID
  LEFT JOIN PP_AD_RESERVE_TB AS PR (NOLOCK) ON PR.LINEADNO = C.LINEADNO
  LEFT JOIN PP_AD_WILLS_RELATION_TB AS WR WITH(NOLOCK) ON WR.LINEADNO = C.LINEADNO
  ' + @strSQLJOIN + ' WHERE C.[VERSION] = ''M'' AND C.GROUP_CD = 14  AND BM.MAG_BRANCH = @MAG_BRANCH '+@strSQLSUB + @strSQLSUB3 + ' OPTION(MAXDOP 1);'

  --PRINT @strSQL
  EXECUTE SP_EXECUTESQL @strSQL,@SQL_PARAM ,
        @BRANCH
,     @strHTMLFLAG
,     @strDTDIV
,     @strStDate
,     @strEnDate
,     @strKey
,     @strWord
,     @BRANCH_FIELD
,     @OPT_CODE
,     @OPT_AREA
,     @STATUS
,     @CONFIRM
,     @OPT_PATH
,     @n4Page
,     @n2PageSize
,     @OPT_STATUS
,     @BRANCH_LOCAL
,     @MAG_BRANCH
,     @EXCEL_YN
,     @chkHOLDOFF


SET @strSQL= 'SELECT TOP (@n4Page * @n2PageSize)
    C.LINEADID, C.REG_DT, dbo.FN_GET_USERID_SECURE(C.USER_ID) AS USER_ID, C.ORDER_NAME, C.START_DT, C.END_DT, C.INPUT_BRANCH, C.LAYOUT_BRANCH
  , ISNULL(P.OPT_CODE,0)
  , CASE WHEN P.PAPER_OPT & 8 = 8 THEN 1 ELSE 0 END AS ACCENT_OPT
  , CASE WHEN P.PAPER_OPT & 16 = 16 THEN 1 ELSE 0 END AS COLOR_OPT
  , PP.LINEADID AS PP_LINEADID, C.DELYN
  , ISNULL(PL.WAIT_LOGO,''-'') AS PUB_LOGO
  , C.DETAILADCODE, C.FIELD_2, C.FIELD_4, ISNULL(PL.WAIT_COMPANY , C.FIELD_6) AS FIELD_6, C.FIELD_9, LO.ORDER_DT AS JOB_ORDER_DT
  , DATEDIFF(D,ISNULL(PR.RESERVE_START_DT, C.START_DT),ISNULL(PR.RESERVE_END_DT, C.END_DT)) + 1 AS DISP_DT
  , LM.ORDER_DT AS MOBILE_ORDER_DT
  , ISNULL(PL.WAIT_TITLE , C.TITLE) AS TITLE, P.OPT_START_DT, P.OPT_END_DT, FC.STATUS, FC.CONFIRM_DT, FC.COMMENT
  , 0 AS CNT
  , ISNULL(P.OPT_I_PRICE,0) AS OPT_I_PRICE
  , ISNULL(P.OPT_P_PRICE,0) AS OPT_P_PRICE
  , ISNULL(I.VIEWTEXT, J.HEADCODEFULLNM) AS LAYOUTCODENAME, OS.MAG_NAME
  , ISNULL(P.OPT_PATH,0) AS OPT_PATH
  , ISNULL(P.MOBILE_OPT_CODE,0) AS MOBILE_OPT_CODE
  , P.DISPLAY_OPT
  , PL.IMPACT_LOGO
  , P.OPT_AREA
  , CUD.COUPON_AMOUNT
  ' + @strSQLFIELD + '
 FROM PP_AD_TB C WITH(NOLOCK)
 JOIN CM_ADMIN_BRANCH_MAPPING_TB AS BM WITH(NOLOCK) ON BM.'+ @BRANCH_FIELD +' = C.'+ @BRANCH_FIELD +'
 JOIN PP_SPOT_AD_JOB_TB AS S WITH(NOLOCK) ON S.LINEADNO = C.LINEADNO
 JOIN CC_SPOT_GOODS_INFO_TB AS SN WITH(NOLOCK) ON SN.S_OPTCODE = S.S_OPTCODE
 JOIN PP_FINDCODE_TB AS CD WITH(NOLOCK) ON CD.CODE4 = C.FINDCODE
 LEFT JOIN PP_OPTION_TB P (NOLOCK) ON C.LINEADNO = P.LINEADNO
 LEFT JOIN PP_LINE_AD_EXTEND_DETAIL_JOB_TB DJ (NOLOCK) ON C.LINEADNO = DJ.LINEADNO
 LEFT JOIN PP_LINE_AD_TB AS PP (NOLOCK) ON PP.LINEADNO = C.LINEADNO
 LEFT JOIN PP_AD_STATISTICS_JOB_TB AS CT (NOLOCK) ON CT.LINEADNO = C.LINEADNO
 LEFT JOIN PP_LOGO_OPTION_TB AS PL (NOLOCK) ON PL.LINEADNO = C.LINEADNO
 LEFT JOIN PP_LISTUP_ORDER_JOB_TB AS LO (NOLOCK) ON LO.LINEADNO = C.LINEADNO
 LEFT JOIN PP_MOBILE_LISTUP_ORDER_JOB_TB AS LM (NOLOCK) ON LM.LINEADNO = C.LINEADNO
 LEFT JOIN PP_FREE_AD_CONFIRM_TB AS FC (NOLOCK) ON FC.LINEADNO = C.LINEADNO
 LEFT JOIN dbo.LAYOUTCLASS_TOT AS I WITH(NOLOCK) ON I.HEADERCODE = C.LAYOUTCODE AND I.BRANCHCODE = C.LAYOUT_BRANCH
 LEFT JOIN dbo.PP_FINDCODE_TB AS J WITH(NOLOCK) ON J.CODE4 = C.FINDCODE
 LEFT JOIN MWDB.dbo.CommonMagUser AS E WITH(NOLOCK) ON E.MAGID = C.MAG_ID
 LEFT JOIN PP_COUPON_USE_DETAIL_TB AS CUD WITH(NOLOCK) ON CUD.LINEADNO = C.LINEADNO AND CUD.PAY_RESULT_YN = ''Y''
 LEFT JOIN PP_AD_RESERVE_TB AS PR (NOLOCK) ON PR.LINEADNO = C.LINEADNO
 LEFT JOIN PP_AD_WILLS_RELATION_TB AS WR WITH(NOLOCK) ON WR.LINEADNO = C.LINEADNO
' + @strSQLJOIN + ' WHERE C.[VERSION] = ''M'' AND C.GROUP_CD = 14 AND BM.MAG_BRANCH = @MAG_BRANCH '+@strSQLSUB + @strSQLSUB3 + ' ORDER BY C.REG_DT DESC OPTION(MAXDOP 1)'

  PRINT @strSQL
  EXECUTE SP_EXECUTESQL @strSQL,@SQL_PARAM ,
        @BRANCH
,     @strHTMLFLAG
,     @strDTDIV
,     @strStDate
,     @strEnDate
,     @strKey
,     @strWord
,     @BRANCH_FIELD
,     @OPT_CODE
,     @OPT_AREA
,     @STATUS
,     @CONFIRM
,     @OPT_PATH
,     @n4Page
,     @n2PageSize
,     @OPT_STATUS
,     @BRANCH_LOCAL
,     @MAG_BRANCH
,     @EXCEL_YN
,     @chkHOLDOFF




