--USE PAPER_NEW
/*************************************************************************************
 *  단위 업무 명 : 벼룩시장 구인구직 맞춤정보 이메일 수신자 목록
 *  작   성   자 : 송이현
 *  작   성   일 : 2018/03/20
 *  수   정   자 : 방순현
 *  수   정   일 : 2021/12/29
 *  설        명 : 조건 추가 - 최근90일 이내 로그인 이력이 있는 회원 21.12.29 (개인화추천 시스템)
 *  주 의  사 항 :
 *  사 용  소 스 :
 *  사 용  예 제 : GET_F_PP_MATCH_AD_EMAIL_RECEIVE_LIST_PROC
 *************************************************************************************/ 
ALTER PROCEDURE [dbo].[GET_F_PP_MATCH_AD_EMAIL_RECEIVE_LIST_PROC]
AS 

 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
 SET NOCOUNT ON


 /*분류코드 써머리*/
 SELECT MAX(CODENM1)AS CODENM1,MAX(CODENM2)AS  CODENM2,'' AS CODENM3,'' AS CODENM4 ,CODE2 AS CODE  
 INTO #TMP_FINDCODE
 FROM PP_FINDCODE_TB WITH(NOLOCK) WHERE  CODE1=4 -- AND USEFLAG = 'Y' 
 GROUP BY CODE2 
 UNION 
 SELECT MAX(CODENM1)AS CODENM1,MAX(CODENM2)AS  CODENM2,MAX(CODENM3) AS CODENM3,'' AS CODENM4 ,CODE3 FROM PP_FINDCODE_TB WITH(NOLOCK) WHERE USEFLAG = 'Y'AND CODE1=4
 GROUP BY CODE3 
 UNION 
 SELECT MAX(CODENM1)AS CODENM1,MAX(CODENM2)AS  CODENM2,MAX(CODENM3) AS CODENM3,MAX(CODENM4) AS CODENM4 ,CODE4 FROM PP_FINDCODE_TB WITH(NOLOCK) WHERE USEFLAG = 'Y'AND CODE1=4
 GROUP BY CODE4 


 /*지역 써머리*/
 SELECT 
 DISTINCT AREA_C_CODE 
 ,CASE WHEN CITY = '' THEN METRO +' 전체' 
    WHEN DONG = '' THEN CITY +' 전체' 
    ELSE DONG 
    END DONG 
 INTO #TMP
 FROM CM_ZIPTXT_CODE WITH(NOLOCK)


 SELECT CM.CUID, CM.USER_NM, CM.EMAIL, ISNULL(ZIP1.DONG
 + CASE WHEN ZIP2.DONG <> '' THEN ',' ELSE '' END + isnull(ZIP2.DONG,'')
 + CASE WHEN ZIP3.DONG <> '' THEN ',' ELSE '' END + isnull(ZIP3.DONG,'')
 + CASE WHEN ZIP4.DONG <> '' THEN ',' ELSE '' END + isnull(ZIP4.DONG,'')
 + CASE WHEN ZIP5.DONG <> '' THEN ',' ELSE '' END + isnull(ZIP5.DONG,''),'')
  AS AREANM_ARRAY,
 (CASE WHEN dbo.fn_GetSplitSeparatorCount(REPLACE((CAST(FINDCODE_1 AS VARCHAR) + ',' + CAST(FINDCODE_2 AS VARCHAR) + ',' + CAST(FINDCODE_3 AS VARCHAR) + ',' + CAST(FINDCODE_4 AS VARCHAR) + ',' + CAST(FINDCODE_5 AS VARCHAR)), ',0', ''), ',') = 0 THEN 1 
     ELSE dbo.fn_GetSplitSeparatorCount(REPLACE((CAST(FINDCODE_1 AS VARCHAR) + ',' + CAST(FINDCODE_2 AS VARCHAR) + ',' + CAST(FINDCODE_3 AS VARCHAR) + ',' + CAST(FINDCODE_4 AS VARCHAR) + ',' + CAST(FINDCODE_5 AS VARCHAR)), ',0', ''), ',') END) AS FINDCODE_COUNT,
 ISNULL(FC1.CodeNm2 + '|' + FC1.CodeNm3 + '|' + FC1.CodeNm4,'') AS FINDCODENM1,
 ISNULL(FC2.CodeNm2 + '|' + FC2.CodeNm3 + '|' + FC2.CodeNm4,'') AS FINDCODENM2,
 ISNULL(FC3.CodeNm2 + '|' + FC3.CodeNm3 + '|' + FC3.CodeNm4,'') AS FINDCODENM3,
 ISNULL(FC4.CodeNm2 + '|' + FC4.CodeNm3 + '|' + FC4.CodeNm4,'') AS FINDCODENM4,
 ISNULL(FC5.CodeNm2 + '|' + FC5.CodeNm3 + '|' + FC5.CodeNm4,'') AS FINDCODENM5
 FROM PP_MATCH_AD_TB AS PMAT 
 LEFT OUTER  JOIN #tmp AS ZIP1 WITH(NOLOCK) ON left(CAST(area_1 AS VARCHAR)+ '000000',8) = ZIP1.AREA_C_CODE 
 LEFT OUTER  JOIN #tmp AS ZIP2 WITH(NOLOCK) ON left(CAST(area_2 AS VARCHAR)+ '000000',8) = ZIP2.AREA_C_CODE 
 LEFT OUTER  JOIN #tmp AS ZIP3 WITH(NOLOCK) ON left(CAST(area_3 AS VARCHAR)+ '000000',8) = ZIP3.AREA_C_CODE 
 LEFT OUTER  JOIN #tmp AS ZIP4 WITH(NOLOCK) ON left(CAST(area_4 AS VARCHAR)+ '000000',8) = ZIP4.AREA_C_CODE 
 LEFT OUTER  JOIN #tmp AS ZIP5 WITH(NOLOCK) ON left(CAST(area_5 AS VARCHAR)+ '000000',8) = ZIP5.AREA_C_CODE 
 LEFT OUTER  JOIN #TMP_FINDCODE AS FC1 WITH(NOLOCK) ON FC1.CODE = FINDCODE_1
 LEFT OUTER  JOIN #TMP_FINDCODE AS FC2 WITH(NOLOCK) ON FC2.CODE = FINDCODE_2
 LEFT OUTER  JOIN #TMP_FINDCODE AS FC3 WITH(NOLOCK) ON FC3.CODE = FINDCODE_3
 LEFT OUTER  JOIN #TMP_FINDCODE AS FC4 WITH(NOLOCK) ON FC4.CODE = FINDCODE_4
 LEFT OUTER  JOIN #TMP_FINDCODE AS FC5 WITH(NOLOCK) ON FC5.CODE = FINDCODE_5
 
 INNER JOIN MEMBERDB.MWMEMBER.dbo.CST_MASTER AS CM  ON PMAT.CUID = CM.CUID  
  INNER JOIN MEMBERDB.MWMEMBER.dbo.CST_MARKETING_AGREEF_TB AS M ON M.CUID = CM.CUID
 WHERE M.AGREEF = 1 -- 마케팅수신동의 
 AND CM.REST_YN = 'N' -- 휴먼회원 제외
 AND CM.OUT_YN = 'N' -- 탈퇴회원 제외
 AND CM.MEMBER_CD = 1 -- 개인회원만 
 AND NOT (CM.EMAIL NOT LIKE '%@%' OR RTRIM(CM.EMAIL) = '') -- 메일형식 오류 필터 
 AND DATEDIFF(DAY , ISNULL(LAST_LOGIN_DT , JOIN_DT) , GETDATE()) <= 90 --최근90일 이내 로그인 이력이 있는 회원 21.12.29 (개인화추천 시스템)
 --AND CM.USERID in ('devsongm1', '0sim22', 'therebirthss', 'therebirthsss', 'mwmobile31', 'therebirths', 'therebirth')
 --AND CM.USERID in ('co372','cbk08')
 ORDER BY PMAT.CUID

--   drop table #TMP_FINDCODE