USE [COMMON]
GO

/****** Object:  Table [dbo].[MM_LONGTERM_UNUSED_TB]    Script Date: 2021-12-10 ¿ÀÈÄ 2:45:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MM_LONGTERM_UNUSED_TB](
	[PKEY] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[USERID] [varchar](50) NOT NULL,
	[USERNAME] [varchar](30) NOT NULL,
	[EMAIL] [varchar](50) NULL,
	[JOIN_DT] [datetime] NULL,
	[LOGIN_DT] [datetime] NULL,
	[REST_DT] [datetime] NULL,
	[OUT_DT] [datetime] NULL,
	[REG_DT] [datetime] NOT NULL,
	[CUID] [int] NULL,
 CONSTRAINT [PK_MM_LONGTERM_UNUSED_TB] PRIMARY KEY CLUSTERED 
(
	[PKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MM_LONGTERM_UNUSED_TB] ADD  CONSTRAINT [DF_MM_LONGTERM_UNUSED_TB_REG_DT]  DEFAULT (getdate()) FOR [REG_DT]
GO


