 --USE PAPER_NEW 
  
/*************************************************************************************  
 *  단위 업무 명 : 예약 광고 게재  
 *  작   성   자 : 정헌수  
 *  작   성   일 : 2016/03/29  
 *  설        명 :  
 *  주 의  사 항 :  
 *  수   정   자 : 김선호  
 *  수   정   일 : 2021/07/27  
 *  수 정  내 용 : 구인구직 등록대행으로 등록한 예약 게재시 템플릿 변경  
 *  사 용  소 스 :  
 *  사 용  예 제 : EXEC BAT_PP_AD_RESERVE_TB_PROC  
 *************************************************************************************/  
  
ALTER PROC [dbo].[BAT_PP_AD_RESERVE_TB_PROC]  
AS  
  
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED  
SET NOCOUNT ON  
  
  
--임시(지도좌표 수정)  
/*update PP_LINE_AD_extend_detail_TB  
   set GMAP_X=0, GMAP_Y=0   
 WHERE GMAP_X='undefined' or GMAP_X='NaN'  
 */   DECLARE @LINEADID INT  
 DECLARE @LINEADNO CHAR(16)  
 DECLARE @INPUTBRANCH INT  
 DECLARE @LAYOUTBRANCH INT  
 DECLARE @RESERVE_START_DT Datetime  
 DECLARE @RESERVE_END_DT Datetime  
 DECLARE @REG_DT DATE   
 DECLARE @TITLE VARCHAR(50)  
 DECLARE @CUID INT  
 DECLARE @GROUP_CD INT  
 DECLARE @PHONE VARCHAR(20)  
 DECLARE @COM_NM VARCHAR(100)  
 DECLARE @DAY INT  
 DECLARE @SENDDATETIME DATETIME  
 DECLARE @KKAO_SEND_YN VARCHAR(1)  
 DECLARE @VERSION CHAR(1)  
 DECLARE @MAG_ID CHAR(30) --관리자 ID  
 DECLARE @BRANCH_NAME VARCHAR(50) --담당지점명  
 DECLARE @BRANCH_PHONE VARCHAR(50) --담당자번호(지점전화번호 대신 담당자번호로 지정)  
 DECLARE @OPTCODE_NAME VARCHAR(50) --상품명  
 DECLARE @OPT_START_DT Datetime --유료시작일  
 DECLARE @OPT_END_DT Datetime --유료종료일  
   
 SET @SENDDATETIME = CONVERT(VARCHAR(10),GETDATE(),120) +' 10:00' --시간 지정할경우 사용  
   
 CREATE TABLE #KAKAO_SEND_TB (  
 LINEADNO CHAR(16)
  ,LINEADID INT  
  ,TITLE VARCHAR(500)  
  ,REG_DT DATE  
  ,START_DT DATE   
  ,END_DT DATE   
  ,GROUP_CD INT   
  ,COM_NM VARCHAR(100)  
  ,PHONE VARCHAR(100)  
  ,CUID INT  
  ,[VERSION] CHAR(1)  
  ,MAG_ID VARCHAR(30)  
  ,BRANCH_NAME VARCHAR (50)  
  ,BRANCH_PHONE VARCHAR(50)  
  ,OPTCODE_NAME VARCHAR (50)  
  ,OPT_START_DT DATE  
  ,OPT_END_DT DATE  
 )  

  
 DECLARE RESULT_CURSOR CURSOR  
 FOR  
  SELECT B.LINEADNO,B.LINEADID, B.INPUT_BRANCH, B.LAYOUT_BRANCH, A.RESERVE_START_DT, A.RESERVE_END_DT, B.TITLE,B.CUID, B.REG_DT, B.GROUP_CD  
   ,(  
    CASE   
     WHEN M.LINEADNO > '' AND ( A.ISALRAM = 0  OR A.ISALRAM IS NULL) THEN 'N' --부동산 다량등록권은 알람 여부에 따라 YN 설정  
     WHEN B.GROUP_CD = 14 AND B.INPUT_BRANCH = 181 THEN 'N'  
     ELSE 'Y'   
    END  
   ) AS KKAO_SEND_YN  
   ,B.[VERSION]  
   ,ISNULL(B.MAG_ID, '') AS MAG_ID  
   ,(  
    CASE   
     WHEN O.OPT_CODE > 0 THEN  
      (SELECT TOP(100) GOODS_NM FROM PP_ONLINE_GOODS_MASTER WHERE GOODS_ID = O.OPT_CODE)  
     ELSE  
      (SELECT TOP(1) GOODS_NM FROM PP_MOBILE_GOODS_MASTER WHERE GOODS_ID = O.MOBILE_OPT_CODE)  
    END  
   ) AS OPTCODE_NAME  
   ,O.OPT_START_DT  
   ,O.OPT_END_DT  
  FROM DBO.PP_AD_RESERVE_TB A WITH(NOLOCK)   
  INNER JOIN PP_AD_TB B WITH(NOLOCK) ON A.LINEADNO = B.LINEADNO  
  LEFT OUTER JOIN PP_ECOMM_RECCHARGE_TB C WITH(NOLOCK) ON B.VERSION='E' AND C.ADID = B.LINEADID AND C.PRODUCT_GBN = 1  
  LEFT OUTER JOIN CY_MULTI_HOUSE_REG_TB M WITH(NOLOCK) ON A.LINEADNO = M.LINEADNO   
    LEFT OUTER JOIN V_PP_JOB_KEYWORDSEARCH_PAY KP WITH(NOLOCK) ON KP.LINEADNO = A.LINEADNO  
  LEFT OUTER JOIN PP_OPTION_TB O WITH(NOLOCK) ON O.LINEADNO = A.LINEADNO  
  WHERE A.RESERVE_START_DT < GETDATE()  
   AND A.RESERVE_END_DT >= CONVERT(VARCHAR(10), GETDATE(), 120)  
   AND A.RESERVE_STAT = '예약'  
   AND B.ENDYN ='N'  
   AND B.DELYN ='N'  
   AND (B.VERSION='M' OR B.PAY_FREE = 1 OR C.PRNAMTOK = 1 OR KP.PRNAMTOK = 1) --등록대행,무료,결제완료,키워드공고결제완료  
   AND B.ISSTORAGE = 0  
     
 OPEN RESULT_CURSOR  
  
 FETCH NEXT FROM RESULT_CURSOR INTO @LINEADNO,@LINEADID, @INPUTBRANCH, @LAYOUTBRANCH,@RESERVE_START_DT,@RESERVE_END_DT, @TITLE, @CUID, @REG_DT , @GROUP_CD,  @KKAO_SEND_YN, @VERSION, @MAG_ID, @OPTCODE_NAME, @OPT_START_DT, @OPT_END_DT  
  
 WHILE(@@FETCH_STATUS = 0)  
 BEGIN  
  
  UPDATE DBO.PP_AD_TB  
    SET START_DT = @RESERVE_START_DT  
     , END_DT = @RESERVE_END_DT  
   WHERE LINEADID = @LINEADID  
    AND INPUT_BRANCH = @INPUTBRANCH  
    AND LAYOUT_BRANCH = @LAYOUTBRANCH  
    
  -- 오늘자 줄광고에서 적용  
  EXECUTE p_SyncIssueData @LINEADID, @INPUTBRANCH, @LAYOUTBRANCH,  'L', 'E'  
    
    UPDATE PP_AD_RESERVE_TB  
     SET RESERVE_STAT = '게재'  
       , MODIFY_DT = GETDATE()  
   WHERE LINEADNO = @LINEADNO  
  
 IF @CUID<> 0 AND @KKAO_SEND_YN ='Y' BEGIN  
  INSERT #KAKAO_SEND_TB (LINEADNO ,LINEADID, TITLE, REG_DT, START_DT, END_DT, GROUP_CD, CUID, [VERSION], MAG_ID, OPTCODE_NAME, OPT_START_DT, OPT_END_DT )  
  SELECT @LINEADNO , @LINEADID, @TITLE, @REG_DT, @RESERVE_START_DT, @RESERVE_END_DT, @GROUP_CD ,@CUID ,@VERSION ,@MAG_ID, @OPTCODE_NAME, @OPT_START_DT, @OPT_END_DT  
    
 END   
    FETCH NEXT FROM RESULT_CURSOR INTO @LINEADNO,@LINEADID, @INPUTBRANCH, @LAYOUTBRANCH,@RESERVE_START_DT,@RESERVE_END_DT, @TITLE, @CUID, @REG_DT , @GROUP_CD,  @KKAO_SEND_YN, @VERSION, @MAG_ID, @OPTCODE_NAME, @OPT_START_DT, @OPT_END_DT  
  
 END  
  
 CLOSE RESULT_CURSOR  


  
 DEALLOCATE RESULT_CURSOR  
 --RETURN --임시로 발송 제거   
   
 /* 카카오 문자 발송 */   
 IF exists (SELECT * FROM #KAKAO_SEND_TB )  
 BEGIN  
  --수신자 번호, 회사명 추가  
  UPDATE A  
  SET PHONE = B.HPHONE  
   ,COM_NM = CASE WHEN A.GROUP_CD = 13 THEN B.USERID ELSE C.COM_NM END   
  FROm #KAKAO_SEND_TB A INNER JOIN MEMBERDB.MWMEMBER.DBO.CST_MASTER B  WITH(NOLOCK)  ON A.cuid = B.CUID   
  LEFT OUTER JOIN MEMBERDB.MWMEMBER.DBO.CST_COMPANY C ON  B.com_id = C.COM_ID  
  
  --등록대행 담당자번호, 지점명 추가  
  UPDATE A  
  SET BRANCH_NAME = F.PartNm  
   ,BRANCH_PHONE = F.phone2  
  FROM #KAKAO_SEND_TB A   
  INNER JOIN FINDDB2.FINDCOMMON.dbo.CommonMagUser AS F WITH(NOLOCK) ON F.MagID = A.MAG_ID  
  
  DECLARE @MSG VARCHAR(4000)  
  ,@URL VARCHAR(1000)  
  ,@URL_BUTTON_TXT VARCHAR(160)  
  ,@FAIL_SUBJECT VARCHAR(160)  
  ,@FAIL_MSG VARCHAR(4000)  
  ,@TEMPLETE_CODE VARCHAR(10)  
    
   DECLARE KAKAO_CURSOR CURSOR  
  FOR  
   SELECT  
    LINEADNO ,LINEADID, TITLE, REG_DT, START_DT, END_DT, GROUP_CD,PHONE, COM_NM, [VERSION], BRANCH_NAME, BRANCH_PHONE, OPTCODE_NAME, OPT_START_DT, OPT_END_DT  
   FROM #KAKAO_SEND_TB  
  OPEN KAKAO_CURSOR  
  
  FETCH NEXT FROM KAKAO_CURSOR INTO @LINEADNO,@LINEADID, @TITLE, @REG_DT, @RESERVE_START_DT, @RESERVE_END_DT, @GROUP_CD, @PHONE, @COM_NM, @VERSION, @BRANCH_NAME, @BRANCH_PHONE, @OPTCODE_NAME, @OPT_START_DT, @OPT_END_DT  
  WHILE(@@FETCH_STATUS = 0)  
  BEGIN  
   SET @TEMPLETE_CODE = (  
    CASE   
     WHEN @GROUP_CD =  13 THEN   
      'MWFa060'   
     WHEN @GROUP_CD =  14 THEN  
      CASE   
       WHEN @VERSION = 'M' THEN          
        'MWFa048' --등록대행  
       ELSE  
        'MWFa020' --이컴  
      END  
    END   
   )  
   SELECT @MSG = KKO_MSG   
     ,@URL = URL  
     ,@URL_BUTTON_TXT = URL_BUTTON_TXT   
     ,@FAIL_SUBJECT = LMS_TITLE  
     ,@FAIL_MSG = LMS_MSG    
   FROM COMDB1.DBO.FN_GET_KKO_TEMPLATE_INFO(@TEMPLETE_CODE)  
  
   IF @TEMPLETE_CODE = 'MWFa048' BEGIN   
    --구인구직 등록대행  
    SET @day = datediff(d, CONVERT(DATETIME, @OPT_START_DT,101), CONVERT(DATETIME, @OPT_END_DT,101)) + 1 --유료상품기간은 +1  
  
    SET @MSG = REPLACE(@MSG,'#{회사명}',@COM_NM)  
    SET @MSG = REPLACE(@MSG,'#{공고제목}',@TITLE)  
    SET @MSG = REPLACE(@MSG,'#{공고번호}',@LINEADID)  
    SET @MSG = REPLACE(@MSG,'#{상품명}',@OPTCODE_NAME)  
    SET @MSG = REPLACE(@MSG,'#{YYYY-MM-DD ~ YYYY-MM-DD}',CONVERT(VARCHAR(10),@OPT_START_DT,120) +' ~ ' + CONVERT(VARCHAR(10),@OPT_END_DT,120))  
    SET @MSG = REPLACE(@MSG,'#{day}', CAST(@DAY AS VARCHAR))  
    SET @MSG = REPLACE(@MSG,'#{공고URL}','https://m.findjob.co.kr/AdDetail/AdDetail?LineADNO='+@LINEADNO)  
    SET @MSG = REPLACE(@MSG,'#{담당지점명}',@BRANCH_NAME)  
    SET @MSG = REPLACE(@MSG,'#{지점번화번호}',@BRANCH_PHONE)  
  

    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{회사명}',@COM_NM)  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{공고제목}',@TITLE)  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{공고번호}',@LINEADID)  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{상품명}',@OPTCODE_NAME)  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{YYYY-MM-DD ~ YYYY-MM-DD}',CONVERT(VARCHAR(10),@OPT_START_DT,120) +' ~ ' + CONVERT(VARCHAR(10),@OPT_END_DT,120))  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{day}', CAST(@DAY AS VARCHAR))
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{공고URL}','https://m.findjob.co.kr/AdDetail/AdDetail?LineADNO='+@LINEADNO) 
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{담당지점명}',@BRANCH_NAME)  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{지점번화번호}',@BRANCH_PHONE)  

      
   END  
   ELSE IF @TEMPLETE_CODE = 'MWFa020' 
   BEGIN   
    SET @DAY = DATEDIFF(D,@RESERVE_START_DT,@RESERVE_END_DT)  
  
    SET @MSG = REPLACE(@MSG,'#{회사명}',@COM_NM)  
    SET @MSG = REPLACE(@MSG,'#{ID}',@COM_NM)  
    SET @MSG = REPLACE(@MSG,'#{공고제목}',@TITLE)  
    SET @MSG = REPLACE(@MSG,'#{공고번호}',@LINEADID)  
    SET @MSG = REPLACE(@MSG,'#{상품명}',@OPTCODE_NAME)  
    SET @MSG = REPLACE(@MSG,'#{등록일}',CONVERT(VARCHAR(10),@REG_DT,120))  
    SET @MSG = REPLACE(@MSG,'#{YYYY-MM-DD ~ YYYY-MM-DD}',CONVERT(VARCHAR(10),@RESERVE_START_DT,120) +' ~ ' + CONVERT(VARCHAR(10),@RESERVE_END_DT,120))  
    SET @MSG = REPLACE(@MSG,'#{day}',@DAY)  
    SET @MSG = REPLACE(@MSG,'#{공고URL}','https://m.findjob.co.kr/AdDetail/AdDetail?LineADNO='+@LINEADNO)  
  

    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{회사명}',@COM_NM)  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{ID}',@COM_NM)--부동산용  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{공고제목}',@TITLE)  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{공고번호}',@LINEADID)  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{상품명}',@OPTCODE_NAME) 
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{등록일}',CONVERT(VARCHAR(10),@REG_DT,120))  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{YYYY-MM-DD ~ YYYY-MM-DD}',CONVERT(VARCHAR(10),@RESERVE_START_DT,120) +' ~ ' + CONVERT(VARCHAR(10),@RESERVE_END_DT,120))  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{day}',@DAY)  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{공고URL}','https://m.findjob.co.kr/AdDetail/AdDetail?LineADNO='+@LINEADNO)  
   END
   ELSE BEGIN  
    SET @DAY = DATEDIFF(D,@RESERVE_START_DT,@RESERVE_END_DT)  
  
    SET @MSG = REPLACE(@MSG,'#{회사명}',@COM_NM)  
    SET @MSG = REPLACE(@MSG,'#{ID}',@COM_NM)  
    SET @MSG = REPLACE(@MSG,'#{TITLE}',@TITLE)  
    SET @MSG = REPLACE(@MSG,'#{광고번호}',@LINEADID)  
    SET @MSG = REPLACE(@MSG,'#{등록일}',CONVERT(VARCHAR(10),@REG_DT,120))  
    SET @MSG = REPLACE(@MSG,'#{YYYY-MM-DD ~ YYYY-MM-DD}',CONVERT(VARCHAR(10),@RESERVE_START_DT,120) +' ~ ' + CONVERT(VARCHAR(10),@RESERVE_END_DT,120))  
    SET @MSG = REPLACE(@MSG,'#{DAY}',@DAY)  
  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{회사명}',@COM_NM)  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{ID}',@COM_NM)--부동산용  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{TITLE}',@TITLE)  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{광고번호}',@LINEADID)  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{등록일}',CONVERT(VARCHAR(10),@REG_DT,120))  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{YYYY-MM-DD ~ YYYY-MM-DD}',CONVERT(VARCHAR(10),@RESERVE_START_DT,120) +' ~ ' + CONVERT(VARCHAR(10),@RESERVE_END_DT,120))  
    SET @FAIL_MSG = REPLACE(@FAIL_MSG,'#{DAY}',@DAY)  
   END  
  
  
   --SET @PHONE = '010-7109-3394'--임시  
     
   
   EXECUTE COMDB1.DBO.PUT_SENDKAKAO_PROC  
     @PHONE    --수신자 전화번호  
     , '080-269-0011'    --송신자 전화번호  
     , @TEMPLETE_CODE    --알림톡 템플릿 코드  
     , @MSG              --알림톡 발송 메시지  
     , @URL              --알림톡 버튼 URL  
     , @URL_BUTTON_TXT   --알림톡 버튼 TEXT  
  
     , @FAIL_SUBJECT    --알림톡 실패시 문자 제목  
     , @FAIL_MSG        --알림톡 실패시 문자 내용  
     --, '5c211bc7dcb8c6a1ee4c7b7ac865389e1115ffe2'  
     --, @SendDateTime  
   --RETURN --임시로 한건만   
    
  FETCH NEXT FROM KAKAO_CURSOR INTO @LINEADNO,@LINEADID, @TITLE, @REG_DT, @RESERVE_START_DT, @RESERVE_END_DT, @GROUP_CD, @PHONE, @COM_NM, @VERSION, @BRANCH_NAME, @BRANCH_PHONE, @OPTCODE_NAME, @OPT_START_DT, @OPT_END_DT  
  END   
  CLOSE KAKAO_CURSOR  
  DEALLOCATE KAKAO_CURSOR  
 END

