  --USE PAPER_NEW


  /*
  SELECT * INTO MOBILE_SERVICE.dbo._MOBILE_PUSH_DEVICE_INFO_20211026
  FROM MOBILE_SERVICE.dbo._MOBILE_PUSH_DEVICE_INFO_20211025 


  SELECT * INTO PAPER_NEW.DBO._PP_MATCH_AD_TB_20211026
  FROM PAPER_NEW.DBO.PP_MATCH_AD_TB
  */

 

 UPDATE A
  SET A.DeviceID = D.DeviceNewID
  from PAPER_NEW.DBO.PP_MATCH_AD_TB A WITH(NOLOCK)  
  join MOBILE_SERVICE.dbo.MOBILE_PUSH_DEVICE_INFO AS D WITH(NOLOCK) on d.DeviceID = a.DeviceID
  AND NOT (A.DeviceID = '' Or A.DeviceID is null)
  AND NOT (D.DeviceNewID = '' Or D.DeviceNewID is  null)

  /*
  select *
  from PP_MATCH_AD_TB a WITH(NOLOCK)  
  join MOBILE_SERVICE.dbo.MOBILE_PUSH_DEVICE_INFO AS D WITH(NOLOCK) on d.DeviceID = a.DeviceID
  AND NOT (A.DeviceID = '' Or A.DeviceID is null)
  AND NOT (D.DeviceNewID = '' Or D.DeviceNewID is  null)
  */