USE MWMEMBER
GO


UPDATE CC
SET CC.CEO_NM = '정회한' , CC.CITY = '' , CC.GU = '' , CC.DONG = '' , CC.ROAD_ADDR_DETAIL =''
FROM CST_COMPANY AS CC
JOIN CST_MASTER AS CM
ON CC.COM_ID = CM.COM_ID
WHERE CM.USERID = '15126139'


UPDATE CC
SET CC.CEO_NM = '강요식' , CC.CITY = '' , CC.GU = '' , CC.DONG = '' ,CC.ADDR2 = '', CC.ROAD_ADDR_DETAIL =''
FROM CST_COMPANY AS CC
JOIN CST_MASTER AS CM
ON CC.COM_ID = CM.COM_ID
WHERE CM.USERID = 'newenergy1'