PP_ONLINE_GOODS_MASTER --pc

PP_MOBILE_GOODS_MASTER --모바일

PP_DISPLAY_GOODS_MASTER --강조옵션

CY_FAT_MASTER_TB --정액권

PP_RESUME_READ_GOODS_MASTER_TB--이력서

GET_M_PP_JOB_KEYWORDSEARCH_OPTION_TB_PROC --키워드 단가 계산 

CC_AGENCY_PRICE_JOB_TB --상품별 가격

