USE [STATS]
GO

/****** Object:  Table [dbo].[BOARD_MANAGER_AUTH_TB]    Script Date: 2023-04-11 ¿ÀÀü 9:58:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BOARD_MANAGER_AUTH_TB](
	[IDX] [int] IDENTITY(1,1) NOT NULL,
	[SECTION] [varchar](10) NULL,
	[SECTIONNAME] [varchar](100) NULL,
	[MANAGERNM] [varchar](max) NULL,
	[MANAGERID] [varchar](max) NULL,
	[MOD_DT] [datetime] NOT NULL,
 CONSTRAINT [PK_BOARD_AUTH_TB] PRIMARY KEY CLUSTERED 
(
	[IDX] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[BOARD_MANAGER_AUTH_TB] ADD  DEFAULT (getdate()) FOR [MOD_DT]
GO


