USE PAPER_NEW
GO

--DROP TABLE #TMP_1

-- 0.백업
SELECT * INTO PP_RESUME_READ_GOODS_COMPANY_AUTH_TB_20230112
FROM PP_RESUME_READ_GOODS_COMPANY_AUTH_TB

-- 1.기업인증 
SELECT CM.CUID , CM.HPHONE 
INTO #TMP_1 
FROM MEMBERDB.MWMEMBER.DBO.CST_MASTER AS CM WITH(NOLOCK) 
JOIN MEMBERDB.MWMEMBER.DBO.CST_COMPANY AS CC WITH(NOLOCK)
ON CM.COM_ID = CC.COM_ID
WHERE CC.BIZLICENSE_CERTIFICATION_YN ='Y'


--SELECT *FROM #TMP_1

--2.이력서인증(이전) 테이블 HPHONE 과 회원테이블(CST_MASTER)의 HPHONE 다른 DATA확인
SELECT *
FROM PP_RESUME_READ_GOODS_COMPANY_AUTH_TB AS PC WITH(NOLOCK)
JOIN #TMP_1 AS TP 
ON PC.CUID = TP.CUID
AND PC.HPHONE <> TP.HPHONE

--3.HPHONE 다른경우 UPDATE
UPDATE PC
SET PC.HPHONE = TP.HPHONE
FROM PP_RESUME_READ_GOODS_COMPANY_AUTH_TB AS PC WITH(NOLOCK)
JOIN #TMP_1 AS TP ON PC.CUID = TP.CUID
AND PC.HPHONE <> TP.HPHONE

