USE PAPER_NEW
GO


-- 0.백업
SELECT * INTO PP_AD_TB_20230206
FROM PP_AD_TB


SELECT AD.LINEADNO  , AD.LINEADID , AD.INPUT_BRANCH , AD.LAYOUT_BRANCH, AD.START_DT,AD.END_DT--, R.*  
INTO #TMP_TB 
FROM PP_AD_TB AS AD WITH(NOLOCK) 
JOIN MWMEMBER.DBO.CST_MASTER AS CM WITH(NOLOCK) ON AD.CUID = CM.CUID 
JOIN MWMEMBER.DBO.CST_COMPANY AS CC WITH(NOLOCK) ON CM.COM_ID = CC.COM_ID 
WHERE (CC.BIZLICENSE_CERTIFICATION_YN ='N' OR CC.BIZLICENSE_CERTIFICATION_YN IS NULL) 
AND DATEDIFF(D,'2023-02-06 00:00:00.000' ,AD.END_DT) >= 0
AND AD.GROUP_CD in (14) -- 구인
AND AD.VERSION IN ('E','M') -- 등록대행,E-COMM만(신문 제외)
AND AD.ENDYN = 'N'  
AND AD.DELYN = 'N'


--SELECT *FROM #TMP_TB


-- 2. 강제 마감 (커서)

--변수 선언
DECLARE 
@INDEX INT,
@LINEADNO NVARCHAR(16),
@LINEADID INT,
@INPUT_BRANCH INT,
@LAYOUT_BRANCH INT

SET @INDEX = 0

DECLARE CUR CURSOR FOR

SELECT
LINEADNO ,
LINEADID ,
INPUT_BRANCH ,
LAYOUT_BRANCH 
FROM #TMP_TB

OPEN CUR --커서 오픈
FETCH NEXT FROM CUR INTO @LINEADNO , @LINEADID , @INPUT_BRANCH ,@LAYOUT_BRANCH  --SELECT 한 값을 변수에 넣음

--커서이용해 한 ROW 씩 읽음
WHILE @@FETCH_STATUS = 0
BEGIN
SET @INDEX = @INDEX + 1

UPDATE PP_AD_TB  
SET ENDYN = 'Y'  
    ,END_DT = GETDATE()  
    ,MOD_DT = GETDATE()  
WHERE LINEADNO = @LINEADNO

EXECUTE p_SyncIssueData @LINEADID, @INPUT_BRANCH, @LAYOUT_BRANCH

FETCH NEXT FROM CUR INTO @LINEADNO , @LINEADID , @INPUT_BRANCH ,@LAYOUT_BRANCH
END

--커서 닫고 초기화
CLOSE CUR
DEALLOCATE CUR