







/*************************************************************************************
 *  단위 업무 명 : E-COMM 관리 리스트 VIEW
 *  작   성   자 : 최 봉 기 (virtualman@mediawill.com)
 *  작   성   일 : 2014/08/21
 *  설        명 : EComm 광고관리 리스트를 동적으로 처리하기에 문자열 Over가 걸려 VIew로 처리
 *  수   정   자 : 신 장 순 (jssin@mediawill.com)
 *  수   정   일 : 2014/11/24
 *  수 정  내 용 : 조회카운트 웹/모바일 구분위해 필드 추가(CNT, CNT_MW, CNT_MA_ANDROID, CNT_MA_IPHONE)
 *  수   정   자 : 방 순 현        
 *  수   정   일 : 2021/10/12 
 *  수 정 내  용 : 로고검수 프로세스 개선
 *  주 의  사 항 :
 *  사 용  소 스 :
 *  사 용  예 제 : SELECT TOP 10 * FROM CY_LINE_AD_MANAGE_JOB_VI where lineadid = 113002328
 *************************************************************************************/
ALTER VIEW [dbo].[CY_LINE_AD_MANAGE_JOB_VI]
AS
SELECT C.LINEADID, C.REG_DT, C.USER_ID, C.ORDER_NAME, C.AREA_A, C.AREA_B, C.AREA_C, C.GROUP_CD
     , R.PRNAMTOK, R.CHARGEKIND, R.CANCELDATE, ISNULL(R.PRNAMT, 0) AS PrnAmt, R.INIPAYTID, R.RECDATE, R.BANKNM, R.ACCOUNTNUM
     , R.RECNM, R.PRODUCT_GBN
     , C.START_DT, C.END_DT, C.INPUT_BRANCH,  C.LAYOUT_BRANCH, ISNULL(P.OPT_CODE, 0) AS OPT_CODE
     , CASE WHEN P.PAPER_OPT & 8 = 8 THEN 1 ELSE 0 END AS ACCENT_OPT, 
            CASE WHEN P.PAPER_OPT & 16 = 16 THEN 1 ELSE 0 END AS COLOR_OPT, CASE WHEN FC.STATUS IS NULL THEN 0 ELSE 1 END AS PAYFREE, C.IDENTYFLAG AS WLOCAL, 
            PP.LINEADID AS PP_LINEADID, ISNULL(CT.HIT_CNT_PC, 0) + ISNULL(CT.HIT_CNT_MO, 0) AS CNT, C.DELYN, ISNULL(PL.WAIT_LOGO, '-') AS PUB_LOGO, C.DETAILADCODE, C.FIELD_2, 
            C.FIELD_4, ISNULL(WAIT_COMPANY , C.FIELD_6) AS FIELD_6, C.FIELD_9, LO.ORDER_DT AS JOB_ORDER_DT, DATEDIFF(D, ISNULL(CONVERT(DATETIME, PR.RESERVE_START_DT), C.START_DT), ISNULL(CONVERT(DATETIME, 
            PR.RESERVE_END_DT), C.END_DT)) + 1 AS DISP_DT, LM.ORDER_DT AS MOBILE_ORDER_DT, FC.STATUS, ISNULL(PL.WAIT_TITLE , C.TITLE) AS TITLE, P.OPT_START_DT, P.OPT_END_DT, FC.CONFIRM_DT, FC.COMMENT, 
            ISNULL(P.MOBILE_OPT_CODE, 0) AS MOBILE_OPT_CODE, FAT.FAT_NM, FAT.USE_CNT + 1 AS USE_CNT, CONVERT(VARCHAR(10), FAT.FAT_REGIST_START_DT, 11) AS FAT_REGIST_START_DT, 
            CONVERT(VARCHAR(10), FAT.FAT_REGIST_END_DT, 11) AS FAT_REGIST_END_DT, PB.BR_SEQ,
                (SELECT BRANCH_CODE
                FROM  dbo.PP_BRAND_BRANCH_TB WITH (NOLOCK)
                WHERE (SEQ = PBA.BRANCH_SEQ)) AS BRANCH_CODE, P.DISPLAY_OPT, PL.IMPACT_LOGO, P.OPT_AREA, C.REG_SUB_BRANCH, C.PHONE, 
            CUD.COUPON_AMOUNT, ISNULL(FAT.STANDARD_CNT, 0) AS STANDARD_CNT, C.NEWMEDIA, PB.BRAND_NAME, FAT.OPT_CODE AS FAT_OPT_CODE, P.PAPER_OPT, 
            ISNULL(LP.IssueCount, 0) AS IssueCount, ISNULL(LP.LINEAMOUNT, 0) AS LINEAMOUNT, LP.LINEADID AS LP_LINEADID, C.FINDCODE, PR.RESERVE_START_DT, PR.RESERVE_END_DT, 
            ISNULL(CT.HIT_CNT_PC, 0) AS CNT_W, ISNULL(CT.HIT_CNT_MO, 0) AS CNT_MW, 0 AS CNT_MA_ANDROID, 0 AS CNT_MA_IPHONE, C.ORDER_EMAIL, C.LINEADNO, C.ENDYN, 
            ISNULL(AP.PARTNERF, 0) AS PARTNERF, C.PAY_FREE, FAT.REGIST_GBN, C.CUID, DE.UPRIGHT_AGREE, C.MAG_ID, ISNULL(CT.APP_CNT_PC, 0) AS APP_CNT_PC, ISNULL(CT.APP_CNT_MO, 0) 
            AS APP_CNT_MO, ISNULL(AP.FEDERATIONF, 0) AS FEDERATIONF, DG.FAT_ID AS FAT_ID_DP, DG.REGIST_ID AS REGIST_ID_DP, DG.DISPLAY_GOODS_ID, DG.DISPLAY_GOODS_ID_CNT, 
            DG.START_DT AS START_DT_DP, DG.END_DT AS END_DT_DP, DG.USE_CNT AS USE_CNT_DP, DG.USE_CNT_TOTAL AS USE_CNT_TOTAL_DP 
     --, (SELECT TOP 1 KEYWORDSEARCHADID FROM dbo.V_PP_JOB_KEYWORDSEARCH_PAY AS KW WITH(NOLOCK) WHERE KW.LINEADNO = C.LINEADNO) AS KEYWORD_SEARCH_ADID
      , NULL AS KEYWORD_SEARCH_ADID
     , 0 AS KW_OPT_CODE
     , NULL AS NEWAD_YN
FROM  dbo.PP_AD_TB AS C WITH (NOLOCK) 
INNER JOIN dbo.PP_OPTION_TB AS P WITH (NOLOCK) ON C.LINEADNO = P.LINEADNO 
LEFT OUTER JOIN dbo.PP_ECOMM_RECCHARGE_TB AS R WITH (NOLOCK) ON R.ADID = C.LINEADID AND R.PRODUCT_GBN = 1 
LEFT OUTER JOIN dbo.PP_LINE_AD_TB AS PP WITH (NOLOCK) ON PP.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.PP_AD_STATISTICS_JOB_TB AS CT WITH (NOLOCK) ON CT.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.PP_LOGO_OPTION_TB AS PL WITH (NOLOCK) ON PL.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.PP_LISTUP_ORDER_JOB_TB AS LO WITH (NOLOCK) ON LO.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.PP_MOBILE_LISTUP_ORDER_JOB_TB AS LM WITH (NOLOCK) ON LM.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.PP_FREE_AD_CONFIRM_TB AS FC WITH (NOLOCK) ON FC.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.CY_FAT_AD_DETAIL_VI AS FAT WITH (NOLOCK) ON FAT.LINEADNO = C.LINEADNO
LEFT OUTER JOIN dbo.PP_BRAND_AD_TB AS PBA WITH (NOLOCK) ON PBA.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.PP_BRAND_TB AS PB WITH (NOLOCK) ON PB.BR_SEQ = PBA.BR_SEQ 
LEFT OUTER JOIN dbo.PP_COUPON_USE_DETAIL_TB AS CUD WITH (NOLOCK) ON CUD.RECCHARGE_SERIAL = R.SERIAL AND CUD.PAY_RESULT_YN = 'Y' 
LEFT OUTER JOIN PAPERREG.dbo.PP_ECOMM_LINEAD_LIST_VI AS LP WITH (NOLOCK) ON LP.ECOMM_LINEADID = C.LINEADID 
LEFT OUTER JOIN dbo.PP_AD_RESERVE_TB AS PR WITH (NOLOCK) ON C.LINEADNO = PR.LINEADNO 
LEFT OUTER JOIN dbo.PP_LINE_AD_EXTEND_DETAIL_JOB_TB AS DE WITH (NOLOCK) ON DE.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.PP_AD_PARTNER_TB AS AP WITH (NOLOCK) ON AP.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.CY_FAT_AD_DISPLAY_GOOD_TB AS DG WITH (NOLOCK) ON DG.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN (SELECT DISTINCT LINEADNO FROM dbo.V_PP_JOB_KEYWORDSEARCH_PAY AS KW WITH(NOLOCK)) AS KW ON KW.LINEADNO = C.LINEADNO
WHERE (C.GROUP_CD = 14) AND (C.NEWMEDIA = 0) AND (C.VERSION = 'E')
  --AND ((C.PAY_FREE = 0 AND R.ADID IS NOT NULL) OR (C.PAY_FREE = 1 AND FAT.LINEADNO IS NOT NULL))
  --AND ((C.PAY_FREE = 0 AND R.ADID IS NOT NULL) OR (C.PAY_FREE = 1 AND FAT.LINEADNO IS NOT NULL AND KW.LINEADNO IS NULL))
  AND (
        (C.PAY_FREE = 0 AND KW.LINEADNO IS NULL) 
        OR (C.PAY_FREE = 1 AND FAT.LINEADNO IS NOT NULL AND KW.LINEADNO IS NULL)
      )

UNION ALL

SELECT C.LINEADID, C.REG_DT, C.USER_ID, C.ORDER_NAME, C.AREA_A, C.AREA_B, C.AREA_C, C.GROUP_CD
     , KW.PRNAMTOK, KW.CHARGEKIND, KW.CANCELDATE, ISNULL(KW.PRNAMT, 0) AS PrnAmt, KW.INIPAYTID, KW.RECDATE, KW.BANKNM, KW.ACCOUNTNUM
     , KW.RECNM, KW.PRODUCT_GBN
     , C.START_DT, C.END_DT, C.INPUT_BRANCH,  C.LAYOUT_BRANCH
     , ISNULL(P.OPT_CODE, 87) AS OPT_CODE
     , 0 AS ACCENT_OPT
     , 0 AS COLOR_OPT
     , CASE WHEN FC.STATUS IS NULL THEN 0 ELSE 1 END AS PAYFREE
     , C.IDENTYFLAG AS WLOCAL
     , PP.LINEADID AS PP_LINEADID
     , ISNULL(CT.HIT_CNT_PC, 0) + ISNULL(CT.HIT_CNT_MO, 0) AS CNT, C.DELYN, ISNULL(PL.WAIT_LOGO, '-') AS PUB_LOGO
     , C.DETAILADCODE, C.FIELD_2, C.FIELD_4, ISNULL(WAIT_COMPANY , C.FIELD_6) AS FIELD_6, C.FIELD_9, LO.ORDER_DT AS JOB_ORDER_DT
     , DATEDIFF(D, C.START_DT, C.END_DT) + 1 AS DISP_DT
     , LM.ORDER_DT AS MOBILE_ORDER_DT, FC.STATUS, ISNULL(PL.WAIT_TITLE , C.TITLE) AS TITLE
     , ISNULL(P.OPT_START_DT, KW.START_DT) AS OPT_START_DT
     , ISNULL(P.OPT_END_DT, KW.END_DT) AS OPT_END_DT
     , FC.CONFIRM_DT, FC.COMMENT
     , P.MOBILE_OPT_CODE, FAT.FAT_NM, FAT.USE_CNT + 1 AS USE_CNT, CONVERT(VARCHAR(10), FAT.FAT_REGIST_START_DT, 11) AS FAT_REGIST_START_DT
     , CONVERT(VARCHAR(10), FAT.FAT_REGIST_END_DT, 11) AS FAT_REGIST_END_DT
     , NULL AS BR_SEQ, NULL AS BRANCH_CODE, 0 AS DISPLAY_OPT, PL.IMPACT_LOGO, 3 AS OPT_AREA, C.REG_SUB_BRANCH, C.PHONE
     , CUD.COUPON_AMOUNT, ISNULL(FAT.STANDARD_CNT, 0) AS STANDARD_CNT, C.NEWMEDIA
     , NULL AS BRAND_NAME, FAT.OPT_CODE AS FAT_OPT_CODE, 0 AS PAPER_OPT
     , 0 AS IssueCount, 0 AS LINEAMOUNT, NULL AS LP_LINEADID, C.FINDCODE
     , PR.RESERVE_START_DT, PR.RESERVE_END_DT
     , ISNULL(CT.HIT_CNT_PC, 0) AS CNT_W, ISNULL(CT.HIT_CNT_MO, 0) AS CNT_MW, 0 AS CNT_MA_ANDROID, 0 AS CNT_MA_IPHONE, C.ORDER_EMAIL, C.LINEADNO, C.ENDYN
     , ISNULL(AP.PARTNERF, 0) AS PARTNERF, C.PAY_FREE, FAT.REGIST_GBN, C.CUID, DE.UPRIGHT_AGREE, C.MAG_ID, ISNULL(CT.APP_CNT_PC, 0) AS APP_CNT_PC, ISNULL(CT.APP_CNT_MO, 0) AS APP_CNT_MO, ISNULL(AP.FEDERATIONF, 0) AS FEDERATIONF
     , NULL AS FAT_ID_DP, NULL AS REGIST_ID_DP, NULL AS DISPLAY_GOODS_ID, NULL AS DISPLAY_GOODS_ID_CNT
     , NULL AS START_DT_DP, NULL AS END_DT_DP, NULL AS USE_CNT_DP, NULL AS USE_CNT_TOTAL_DP 
     , KW.KEYWORDSEARCHADID AS KEYWORD_SEARCH_ADID
     , 87 AS KW_OPT_CODE
     , KW.NEWAD_YN
FROM  dbo.V_PP_JOB_KEYWORDSEARCH_PAY AS KW WITH(NOLOCK)
LEFT OUTER JOIN dbo.PP_AD_TB AS C WITH (NOLOCK) ON C.LINEADNO = KW.LINEADNO
LEFT OUTER JOIN dbo.PP_OPTION_TB AS P WITH (NOLOCK) ON C.LINEADNO = P.LINEADNO 
LEFT OUTER JOIN dbo.PP_LINE_AD_TB AS PP WITH (NOLOCK) ON PP.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.PP_AD_STATISTICS_JOB_TB AS CT WITH (NOLOCK) ON CT.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.PP_LOGO_OPTION_TB AS PL WITH (NOLOCK) ON PL.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.PP_LISTUP_ORDER_JOB_TB AS LO WITH (NOLOCK) ON LO.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.PP_MOBILE_LISTUP_ORDER_JOB_TB AS LM WITH (NOLOCK) ON LM.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.PP_FREE_AD_CONFIRM_TB AS FC WITH (NOLOCK) ON FC.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.CY_FAT_AD_DETAIL_VI AS FAT WITH (NOLOCK) ON FAT.LINEADNO = C.LINEADNO
LEFT OUTER JOIN dbo.PP_COUPON_USE_DETAIL_TB AS CUD WITH (NOLOCK) ON CUD.RECCHARGE_SERIAL = KW.SERIAL AND CUD.PAY_RESULT_YN = 'Y' 
LEFT OUTER JOIN dbo.PP_LINE_AD_EXTEND_DETAIL_JOB_TB AS DE WITH (NOLOCK) ON DE.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.PP_AD_PARTNER_TB AS AP WITH (NOLOCK) ON AP.LINEADNO = C.LINEADNO 
LEFT OUTER JOIN dbo.PP_AD_RESERVE_TB AS PR WITH (NOLOCK) ON PR.LINEADNO = C.LINEADNO 
WHERE (C.GROUP_CD = 14) AND (C.NEWMEDIA = 0) AND (C.VERSION = 'E')







