
SELECT CC.*    
   FROM CST_COMPANY AS CC WITH(NOLOCK)    
 JOIN CST_MASTER AS CM ON CC.COM_ID = CM.COM_ID     
 LEFT JOIN CST_JOIN_INFO AS CJI ON CM.CUID = CJI.CUID    
 LEFT JOIN PAPER_NEW.DBO.PP_BRAND_BRANCH_TB AS BBT ON CM.CUID = BBT.CUID AND BBT.CANCEL_YN = 'N'    
 WHERE BIZLICENSE_CERTIFICATION_YN IS NOT NULL     
 AND (CC.BIZLICENSE_REGDATE >= '2023-01-12 00:00:00' AND CC.BIZLICENSE_REGDATE <= '2023-01-12 23:59:59')
 AND CC.BIZ_CERTIFICATION_TYPE <> 'O'
 AND CC.BIZ_CERTIFICATION_TYPE <> 'N'