SELECT AD.LINEADNO 
FROM PP_AD_TB AS AD WITH(NOLOCK)
LEFT JOIN MWMEMBER.DBO.CST_MASTER AS CM WITH(NOLOCK) ON AD.CUID = CM.CUID
LEFT JOIN MWMEMBER.DBO.CST_COMPANY AS CC WITH(NOLOCK) ON CM.COM_ID = CC.COM_ID
WHERE CC.BIZLICENSE_CERTIFICATION_YN ='N'
AND AD.END_DT > '2023-02-06 00:00:00.000'