USE [PARTNERSHIP]
GO

/****** Object:  StoredProcedure [dbo].[GET_API_AD_DATA_PROC]    Script Date: 2023-02-22 오전 11:11:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






/*************************************************************************************
 *  단위 업무 명 : 벼룩시장 광고 API 가져오기 (게재기준)
 *  작   성   자 : 신 장 순 (jssin@mediawill.com)
 *  작   성   일 : 2015/04/02
 *  설        명 : 벼룩시장 광고를 가져와 PARTNERSHIP DB로 이관한다
 *  작   성   자 : 김 성 윤 
 *  작   성   일 : 2021/11/16
 *  설        명 : 업직종개편으로인한 신규 업직종 코드 컬럼 추가 
 *  작   성   자 : 배진용 
 *  작   성   일 : 2022/05/30
 *  설        명 : emailf 고정값으로 0 및 이메일 빈값으로 수정
 *  주 의  사 항 : 
 *  사 용  소 스 :
 *  사 용  예 제 :
확인쿼리
SELECT COUNT(*) FROM API_LINE_AD_TB
SELECT COUNT(*) FROM API_LOGO_OPTION_TB
SELECT COUNT(*) FROM API_LINE_AD_FINDCODE_TB
SELECT COUNT(*) FROM API_LINE_AD_AREA_TB
SELECT COUNT(*) FROM API_LINE_AD_EXTEND_DETAIL_JOB_TB
SELECT COUNT(*) FROM API_AD_EC_DATA_JOB_TB
SELECT COUNT(*) FROM API_AD_SUBWAY_DATA_TB
SELECT COUNT(*) FROM API_LINE_AD_EXTEND_DETAIL_TB
EXEC GET_API_AD_DATA_PROC
 *************************************************************************************/
CREATE PROC [dbo].[GET_API_AD_DATA_PROC]
AS
BEGIN
  SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
  SET NOCOUNT ON

  /* 기존 데이터 삭제 */
  TRUNCATE TABLE API_LINE_AD_TB
  TRUNCATE TABLE API_LOGO_OPTION_TB
  TRUNCATE TABLE API_LINE_AD_FINDCODE_TB
  TRUNCATE TABLE API_LINE_AD_AREA_TB
  TRUNCATE TABLE API_LINE_AD_EXTEND_DETAIL_JOB_TB
  TRUNCATE TABLE API_AD_EC_DATA_JOB_TB
  TRUNCATE TABLE API_AD_SUBWAY_DATA_TB
  TRUNCATE TABLE API_LINE_AD_EXTEND_DETAIL_TB  

  BEGIN TRY

    SELECT A.LINEADNO
          ,A.LINEADID
          ,A.INPUT_BRANCH
          ,A.LAYOUT_BRANCH
          ,A.GROUP_CD
          ,A.ORDER_NAME
          ,A.FIELD_3
          ,A.FIELD_6
          ,A.START_DT
          ,A.END_DT
          ,A.[VERSION]
          ,A.REG_DT
          ,A.MOD_DT
          ,PAPER_NEW.[dbo].[fn_DelSpecCharTitle](A.TITLE,'E') AS TITLE
          ,A.ORDER_EMAIL
          ,A.PHONE
          ,A.PHONE_MOBILE
          ,A.VNSNO
          ,A.IDENTYFLAG
          ,A.USER_ID
          ,A.AREA_A
          ,A.AREA_B
          ,A.AREA_C
          ,CASE WHEN C.LINEADNO IS NOT NULL THEN 1 ELSE 0 END AS FREE_AD_F
          ,PAPT.PARTNERF AS ALBA_PARTNER
          ,PAPT.KINFAF AS KINFA_PARTNER
          ,PAPT.SENIORTVF AS SENIORTV_PARTNER
          ,A.EX_CONTENTS
      INTO #INTO_REAL_PP_LINE_AD_TB
      FROM [PAPER_NEW].[DBO].[PP_LINE_AD_TB] A      
      LEFT JOIN [PAPER_NEW].[DBO].[PP_FREE_AD_CONFIRM_TB] C ON A.LINEADNO = C.LINEADNO
      LEFT JOIN [PAPER_NEW].[DBO].PP_AD_PARTNER_TB AS PAPT WITH(NOLOCK) ON A.LINEADNO = PAPT.LINEADNO
     WHERE A.GROUP_CD = 14
       AND A.[VERSION] IN ('E', 'M')  -- eComm/등록대행
       AND (PAPT.PARTNERF = 1 OR PAPT.KINFAF = 1 OR PAPT.SENIORTVF = 1)

    /* 2020.09.03, 알바천국 요청, 특정단어 제외 - 시작 */
    DELETE A
    -- SELECT *
      FROM #INTO_REAL_PP_LINE_AD_TB A
     WHERE A.EX_CONTENTS LIKE '%채권추심%'
    /* 알바천국 요청, 특정단어 제외 - 끝 */

    /* 중복공고 제외 - START    
    2018.06.20, 정액권 공고, 무료공고 만 중복제거로 변경 
  2019.01.09, 근무지1 중복체크 추가(동일 아이디의 동일 제목, 근무지1이 다른 공고가 API 데이터에 추가 되도록 수정함) */     
    
    -- 정액권 공고 제외
    SELECT USER_ID, TITLE, AREA_A, AREA_B, AREA_C, MAX(LINEADID) AS LINEADID
      INTO #INTO_AD
      FROM #INTO_REAL_PP_LINE_AD_TB
     WHERE INPUT_BRANCH = 181
     GROUP BY USER_ID, TITLE, AREA_A, AREA_B, AREA_C
    
    DELETE
    -- SELECT *
      FROM #INTO_REAL_PP_LINE_AD_TB
     WHERE LINEADID NOT IN (SELECT LINEADID FROM #INTO_AD)
       AND INPUT_BRANCH = 181

    -- 무료 공고 제외
    SELECT USER_ID, TITLE, AREA_A, AREA_B, AREA_C, MAX(LINEADID) AS LINEADID
      INTO #INTO_AD_FREE
      FROM #INTO_REAL_PP_LINE_AD_TB
     WHERE FREE_AD_F = 1
     GROUP BY USER_ID, TITLE, AREA_A, AREA_B, AREA_C
    
    DELETE
    -- SELECT *
      FROM #INTO_REAL_PP_LINE_AD_TB
     WHERE LINEADID NOT IN (SELECT LINEADID FROM #INTO_AD_FREE)
       AND FREE_AD_F = 1
    /* 중복공고 제외 - END */

    /* LOGO OPTION 데이터 입력 */
    INSERT INTO API_LOGO_OPTION_TB (LINEADNO, PUB_LOGO)
    SELECT A.LINEADNO, PUB_LOGO
    FROM [PAPER_NEW].[dbo].[PP_LOGO_OPTION_TB] A
    JOIN #INTO_REAL_PP_LINE_AD_TB B ON B.LINEADNO = A.LINEADNO

    /* 다중 인터넷분류 데이터 입력 */
    SELECT A.LINEADNO
          ,A.FINDCODE
          ,MIN(A.[ORDER]) AS [ORDER]
          ,'L' AS AD_KIND
    INTO #TMP_FINDCODE
    FROM [PAPER_NEW].[dbo].[PP_LINE_AD_FINDCODE_TB] A
    JOIN #INTO_REAL_PP_LINE_AD_TB B ON B.LINEADNO = A.LINEADNO   
    GROUP BY A.LINEADNO,A.FINDCODE

    INSERT INTO API_LINE_AD_FINDCODE_TB (
           LINEADNO
          ,FINDCODE
          ,FINDCODE_NEW
          ,[ORDER]
          ,AD_KIND
    )
    SELECT X.LINEADNO
          ,X.AS_FINDCODE
          ,X.TO_FINDCODE
          ,X.[ORDER]
          ,X.AD_KIND
      FROM (
            SELECT DISTINCT
                   A.LINEADNO
                  ,(SELECT TOP 1 AS_FINDCODE FROM PP_FINDCODE_TO_AS_TB C WITH(NOLOCK) WHERE TO_FINDCODE = A.FINDCODE) AS AS_FINDCODE
                  ,A.FINDCODE AS TO_FINDCODE
                  ,A.[ORDER]
                  ,A.AD_KIND
            FROM #TMP_FINDCODE A
            ) X
    WHERE X.AS_FINDCODE IS NOT NULL
    ORDER BY X.LINEADNO, X.[ORDER]

    DROP TABLE #TMP_FINDCODE

    /* 다중 근무지역 데이터 입력 */
    INSERT INTO API_LINE_AD_AREA_TB (
           LINEADNO
          ,AREA_A
          ,AREA_B
          ,AREA_C
          ,AREA_DONG
          ,AREA_DETAIL
          ,[ORDER]
          ,AD_KIND
          ,AREA_C_CODE
          ,AREA_C_GROUP
          ,AREA_B_TEMP
          ,AREA_C_TEMP
          ,AREA_A_CODE
          ,AREA_B_CODE
          ,AREA_A_TEMP
          ,LIVEYN
    )
    SELECT A.LINEADNO
          ,A.AREA_A          
          ,A.AREA_B
          ,A.AREA_C
          ,A.AREA_DONG
          ,CASE WHEN A.AREA_B <> '전지역' AND A.AREA_C <> '전지역' THEN 
                CASE WHEN A.[ORDER] = 1 THEN C.ADDRESS_DETAIL ELSE '' END 
           ELSE '' END AS AREA_DETAIL
          ,A.[ORDER]
          ,A.AD_KIND
          ,A.AREA_C_CODE
          ,A.AREA_C_GROUP
          ,A.AREA_B_TEMP
          ,A.AREA_C_TEMP
          ,A.AREA_A_CODE
          ,A.AREA_B_CODE
          ,A.AREA_A_TEMP
          ,A.LIVEYN
    FROM [PAPER_NEW].[dbo].[PP_LINE_AD_AREA_1DAY_TB] A
    JOIN #INTO_REAL_PP_LINE_AD_TB B ON B.LINEADNO = A.LINEADNO
    LEFT JOIN PAPER_NEW.dbo.PP_LINE_AD_EXTEND_DETAIL_JOB_1DAY_TB C ON C.LINEADNO = A.LINEADNO
   WHERE A.[ORDER] < 100
   ORDER BY A.LINEADNO 

    /* 게재데이터 섹션(구인구직)상세 입력 */
    INSERT INTO API_LINE_AD_EXTEND_DETAIL_JOB_TB (
           LINEADNO
          ,SUBWAYF
          ,SUBWAYLINE
          ,SUBWAYNAME
          ,SUBWAYCODE
          ,AGE
          ,SEXF
          ,PAYF
          ,PAYFROM
          ,PAYTO
          ,WORKTIMEF
          ,WORKTIMEFROM
          ,WORKTIMETO
          ,HOMEF
          ,PARTTIMEF
          ,WEEKENDF
          ,PHONEF
          ,PHONE
          ,EMAILF
          ,EMAIL
          ,MOBILEF
          ,MOBILE
          ,URLF
          ,URL
          ,RECRUIT_END_DT
          ,AD_KIND
          ,PHONE1_VIEWF
          ,PHONE1
          ,PHONE2_VIEWF
          ,PHONE2
          ,EMAIL_VIEWF
          ,AGEF
          ,AGEFROM
          ,AGETO
          ,AGESUB_JUBU
          ,AGESUB_MIDDLE
          ,AGESUB_MINORITY
          ,MAINBIZ
          ,EDULEVEL
          ,CAREERF
          ,CAREERFROM
          ,CAREERTO
          ,WORK_MAIN
          ,WORK_SUB
          ,WORK_OUT
          ,PAYTYPE
          ,REGULAREMPF
          ,VISITF
          ,CI_ZIPID
          ,CI_ADDRDETAIL
          ,ONLINEF
          ,SERVICE_PERIOD
          ,SUBMIT_DOC
          ,WORK_APPOINT
          ,ADDRESS_JIBUN
          ,ADDRESS_ROAD
          ,ADDRESS_DETAIL
          ,PAY_POSSIBLE
          ,WORK_FREELANCER
          ,PAY_COMPANY_RULES
          ,PAY_COMPANY_RULES_ETC
          ,FAX
          ,FAXF
          ,DAY_WEEK
          ,DAY_WEEK_OPTION
          ,DAY_WEEK_OPTION_ETC
          ,CI_BIZNO
          ,WORKTIMEDISPLAY
          ,DAY_WEEK_OPTION2
          ,RESTTIMEF
          ,REAL_WORKTIME
          ,REAL_WORKTIMEDISPLAY
          ,WORKTIME_CODE
          ,PAYTO_OVERF
          ,WORK_TAKE_CHARGE
          ,COMPANY_URL
          ,MAP_VIEW_YN
          ,OUTF
    )
    SELECT A.LINEADNO
          ,A.SUBWAYF
          ,A.SUBWAYLINE
          ,A.SUBWAYNAME
          ,A.SUBWAYCODE
          ,A.AGE
          ,A.SEXF
          ,A.PAYF
          ,A.PAYTO PAYFROM
          ,A.PAYTO
          ,A.WORKTIMEF
          ,A.WORKTIMEFROM
          ,A.WORKTIMETO
          ,A.HOMEF
          ,A.PARTTIMEF
          ,A.WEEKENDF
          ,A.PHONEF
          ,A.PHONE

          , 0 as EMAILF
          , '' AS EMAIL

          ,A.MOBILEF
          ,A.MOBILE
          ,A.URLF
          ,A.URL
          ,A.RECRUIT_END_DT
          ,A.AD_KIND
          ,A.PHONE1_VIEWF
          ,A.PHONE1
          ,A.PHONE2_VIEWF
          ,A.PHONE2
          ,A.EMAIL_VIEWF
          ,A.AGEF
          ,A.AGEFROM
          ,A.AGETO
          ,A.AGESUB_JUBU
          ,A.AGESUB_MIDDLE
          ,A.AGESUB_MINORITY
          ,A.MAINBIZ
          ,A.EDULEVEL
          ,A.CAREERF
          ,A.CAREERFROM
          ,A.CAREERTO
          ,A.WORK_MAIN
          ,A.WORK_SUB
          ,A.WORK_OUT
          ,A.PAYTYPE
          ,A.REGULAREMPF
          ,A.VISITF
          ,A.CI_ZIPID
          ,A.CI_ADDRDETAIL
          ,A.ONLINEF
          ,A.SERVICE_PERIOD
          ,A.SUBMIT_DOC
          ,A.WORK_APPOINT
          ,A.ADDRESS_JIBUN
          ,A.ADDRESS_ROAD
          ,A.ADDRESS_DETAIL
          ,A.PAY_POSSIBLE
          ,A.WORK_FREELANCER
          ,A.PAY_COMPANY_RULES
          ,A.PAY_COMPANY_RULES_ETC
          ,A.FAX
          ,A.FAXF
          ,A.DAY_WEEK
          ,A.DAY_WEEK_OPTION
          ,A.DAY_WEEK_OPTION_ETC
          ,CASE WHEN A.CI_BIZNO IS NULL OR A.CI_BIZNO = '' THEN 
            (
             SELECT TOP 1 replace(F.REGISTER_NO, '-', '') 
              FROM PAPER_NEW.DBO.PP_LINE_AD_TB D
              JOIN MEMBERDB.MWMEMBER.DBO.CST_MASTER E ON E.CUID = D.CUID
              JOIN MEMBERDB.MWMEMBER.DBO.CST_COMPANY F ON F.COM_ID = E.COM_ID
             WHERE D.USER_ID = B.USER_ID
            )
           ELSE A.CI_BIZNO END AS CI_BIZNO
          ,A.WORKTIMEDISPLAY
          ,A.DAY_WEEK_OPTION2
          ,A.RESTTIMEF
          ,A.REAL_WORKTIME
          ,A.REAL_WORKTIMEDISPLAY
          ,A.WORKTIME_CODE
          ,A.PAYTO_OVERF
          ,A.WORK_TAKE_CHARGE
          ,A.COMPANY_URL
          ,A.MAP_VIEW_YN
          ,A.OUTF
    FROM [PAPER_NEW].[dbo].[PP_LINE_AD_EXTEND_DETAIL_JOB_TB] A
    JOIN #INTO_REAL_PP_LINE_AD_TB B ON B.LINEADNO = A.LINEADNO

    /* 우대사항 입력 */
    INSERT INTO API_AD_EC_DATA_JOB_TB (
           LINEADNO
          ,EC_CHOBO
          ,EC_JUBU
          ,EC_JANGNYUN
          ,EC_JANGAE
          ,EC_HUHAK
          ,EC_WOIKUK
          ,EC_GYOPO
          ,EC_DONGJONG
          ,EC_ENGLISH
          ,EC_CHINESE
          ,EC_AUTOLICENSE
          ,EC_BIKELICENSE
          ,EC_CAROWNER
          ,EC_COMPUTER
          ,EC_LONGTIME
          ,EC_INGUNE
          ,EC_ABOUTLICENSE
          ,EC_ARMY
          ,EC_SUKSIK
          ,EX_SUBWORK
          ,AD_KIND
          ,LIVEYN
    )
    SELECT A.LINEADNO
          ,A.EC_CHOBO
          ,A.EC_JUBU
          ,A.EC_JANGNYUN
          ,A.EC_JANGAE
          ,A.EC_HUHAK
          ,A.EC_WOIKUK
          ,A.EC_GYOPO
          ,A.EC_DONGJONG
          ,A.EC_ENGLISH
          ,A.EC_CHINESE
          ,A.EC_AUTOLICENSE
          ,A.EC_BIKELICENSE
          ,A.EC_CAROWNER
          ,A.EC_COMPUTER
          ,A.EC_LONGTIME
          ,A.EC_INGUNE
          ,A.EC_ABOUTLICENSE
          ,A.EC_ARMY
          ,A.EC_SUKSIK
          ,A.EX_SUBWORK
          ,A.AD_KIND
          ,A.LIVEYN
    FROM [PAPER_NEW].[dbo].[PP_AD_EC_DATA_JOB_TB] A
    JOIN #INTO_REAL_PP_LINE_AD_TB B ON B.LINEADNO = A.LINEADNO





    /* 지하철 정보 입력 */
    INSERT INTO API_AD_SUBWAY_DATA_TB (
           LINEADNO
          ,SUBWAY_CODE
          ,GATE_NUMBER
          ,ETC
          ,[ORDER]
          ,AD_KIND
          ,LIVEYN
    )
    SELECT A.LINEADNO
          ,A.SUBWAY_CODE
          ,A.GATE_NUMBER
          ,A.ETC
          ,A.[ORDER]
          ,A.AD_KIND
          ,A.LIVEYN
    FROM [PAPER_NEW].[dbo].[PP_AD_SUBWAY_DATA_TB] A
    JOIN #INTO_REAL_PP_LINE_AD_TB B ON B.LINEADNO = A.LINEADNO

    /* 게재데이터 상세 입력 */
    INSERT INTO API_LINE_AD_EXTEND_DETAIL_TB (
           LINEADNO
          ,EX_CONTENTS
          ,EX_IMAGE_1
          ,EX_IMAGE_2
          ,EX_IMAGE_3
          ,EX_IMAGE_4
          ,MAP_X
          ,MAP_Y
          ,REG_KIND
          ,GMAP_X
          ,GMAP_Y
          ,HTML_FLAG
    )
    SELECT A.LINEADNO
          --,A.EX_CONTENTS
          ,REPLACE(REPLACE(REPLACE(CAST(A.EX_CONTENTS AS NVARCHAR(MAX)), '´', '"'), '˝', '"'), 'src="/UploadFiles/', 'src="http://uimg.findjob.co.kr/UploadFiles/') AS EX_CONTENTS
          ,A.EX_IMAGE_1
          ,A.EX_IMAGE_2
          ,A.EX_IMAGE_3
          ,A.EX_IMAGE_4
          ,A.MAP_X
          ,A.MAP_Y
          ,A.REG_KIND
          ,A.GMAP_X
          ,A.GMAP_Y
          ,A.HTML_FLAG
    FROM [PAPER_NEW].[dbo].[PP_LINE_AD_EXTEND_DETAIL_TB] A
    JOIN #INTO_REAL_PP_LINE_AD_TB B ON B.LINEADNO = A.LINEADNO

    /* 게재데이터 입력 */
    INSERT INTO API_LINE_AD_TB (
           LINEADNO
          ,LINEADID
          ,INPUT_BRANCH
          ,LAYOUT_BRANCH
          ,GROUP_CD
          ,ORDER_NAME
          ,FIELD_3
          ,FIELD_6
          ,START_DT
          ,END_DT
          ,[VERSION]
          ,REG_DT
          ,MOD_DT
          ,TITLE
          ,ORDER_EMAIL
          ,PHONE
          ,PHONE_MOBILE
          ,VNSNO
          ,IDENTYFLAG
          ,FREE_AD_F
          ,ALBA_PARTNER
          ,KINFA_PARTNER
    ,SENIORTV_PARTNER
    )
    SELECT LINEADNO
          ,LINEADID
          ,INPUT_BRANCH
          ,LAYOUT_BRANCH
          ,GROUP_CD
          ,ORDER_NAME
          ,FIELD_3
          ,FIELD_6
          ,START_DT
          ,END_DT
          ,[VERSION]
          ,REG_DT
          ,MOD_DT
          ,TITLE
          ,ORDER_EMAIL
          ,PHONE
          ,PHONE_MOBILE
          ,VNSNO
          ,IDENTYFLAG
          ,FREE_AD_F
          ,ALBA_PARTNER
          ,KINFA_PARTNER
    , CASE WHEN [VERSION] = 'E' THEN SENIORTV_PARTNER ELSE 0 END AS SENIORTV_PARTNER
    FROM #INTO_REAL_PP_LINE_AD_TB

  END TRY

  BEGIN CATCH
    /* 기존 데이터 삭제 */
    TRUNCATE TABLE API_LINE_AD_TB
    TRUNCATE TABLE API_LOGO_OPTION_TB
    TRUNCATE TABLE API_LINE_AD_FINDCODE_TB
    TRUNCATE TABLE API_LINE_AD_AREA_TB
    TRUNCATE TABLE API_LINE_AD_EXTEND_DETAIL_JOB_TB
    TRUNCATE TABLE API_AD_EC_DATA_JOB_TB
    TRUNCATE TABLE API_AD_SUBWAY_DATA_TB
    TRUNCATE TABLE API_LINE_AD_EXTEND_DETAIL_TB

    DECLARE @MSG NVARCHAR(500)
    SET @MSG = '[벼룩시장] 벼룩시장 API 공고 데이터 이관 오류'
    EXECUTE COMDB1.DBO.PUT_SENDSMS_PROC '0230190213','FA SYSTEM','개발담당','01033931420',@MSG            -- 이근우
  END CATCH

  DROP TABLE #INTO_REAL_PP_LINE_AD_TB

END
GO








USE [PARTNERSHIP]
GO

/****** Object:  StoredProcedure [dbo].[GET_API_AD_DETAIL_PROC]    Script Date: 2023-02-22 오전 11:11:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/*************************************************************************************
 *  단위 업무 명 : 벼룩시장 광고 API (Detail)
 *  작   성   자 : 신 장 순 (jssin@mediawill.com)
 *  작   성   일 : 2014/10/22
 *  설        명 : 벼룩시장 광고 상세내용(API 사용)
 *  주 의  사 항 :
 *  사 용  소 스 :
 *  사 용  예 제 :
 EXEC GET_API_AD_DETAIL_PROC 3543629, 181, 180

 EXEC GET_API_AD_DETAIL_PROC 4687573, 181, 180, '0112277854090090'
 SELECT * FROM API_LINE_AD_TB
 *************************************************************************************/
CREATE PROC [dbo].[GET_API_AD_DETAIL_PROC]
 @lineadid     INT     = 0
, @input_branch   TINYINT   = 0
, @layout_branch  TINYINT   = 0
, @lineadno     VARCHAR(16) = ''
, @SITE_ID   VARCHAR(50) = ''
, @SITE_AUTH_NO VARCHAR(100) = ''
AS
BEGIN

 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

 IF LEN(@lineadno) = 0
  BEGIN
   SET @lineadno = RIGHT('0000000000' + CONVERT(VARCHAR(10), @lineadid), 10)  + RIGHT('000' + CONVERT(VARCHAR(3), @input_branch), 3) +  RIGHT('000' + CONVERT(VARCHAR(3), @layout_branch), 3)
  END

 DECLARE @USERID VARCHAR(50)  = ''
  DECLARE @CUID INT = 0
 SELECT @USERID = [USER_ID]
       , @CUID = CUID
  FROM PAPER_NEW.DBO.PP_AD_TB WITH (NOLOCK)
  WHERE LINEADNO = @lineadno


 DECLARE @METRO  VARCHAR(50)  = ''
 DECLARE @CITY   VARCHAR(50)  = ''
 DECLARE @DONG   VARCHAR(50)  = ''
 DECLARE @ADDR_D  VARCHAR(100) = ''
 DECLARE @COM_NM  VARCHAR(50)  = ''
 DECLARE @HOMEPAGE VARCHAR(100) = ''
 DECLARE @MAIN_BIZ VARCHAR(100) = ''

 BEGIN TRY
  SELECT @COM_NM  = CASE WHEN A.USERID IN ('NoMember', 'a2013') THEN '' ELSE B.COM_NM END
     , @HOMEPAGE = CASE WHEN A.USERID IN ('NoMember', 'a2013') THEN '' ELSE B.HOMEPAGE END
     , @METRO   = CASE WHEN A.USERID IN ('NoMember', 'a2013') THEN '' ELSE B.CITY END
     , @CITY   = CASE WHEN A.USERID IN ('NoMember', 'a2013') THEN '' ELSE B.GU END
     , @DONG   = CASE WHEN A.USERID IN ('NoMember', 'a2013') THEN '' ELSE B.DONG END
     , @MAIN_BIZ = CASE WHEN A.USERID IN ('NoMember', 'a2013') THEN '' ELSE C.MAIN_BIZ END
     , @ADDR_D  = CASE WHEN A.USERID IN ('NoMember', 'a2013') THEN '' ELSE B.ADDR1 END
  FROM MEMBERDB.MWMEMBER.DBO.CST_MASTER A
    JOIN MEMBERDB.MWMEMBER.DBO.CST_COMPANY B ON A.COM_ID = B.COM_ID
    JOIN MEMBERDB.MWMEMBER.DBO.CST_COMPANY_JOB C ON B.COM_ID = C.COM_ID
   WHERE A.CUID = @CUID
 END TRY
 BEGIN CATCH
 END CATCH

 SELECT A.LINEADNO
    , A.LINEADID
    , A.INPUT_BRANCH
    , A.LAYOUT_BRANCH
    , A.REG_DT
    , A.MOD_DT
       , A.FIELD_6
    , A.ORDER_NAME
    , C.PHONE1_VIEWF
    , C.PHONE1
    , C.PHONE2_VIEWF
    , C.PHONE2
    , C.EMAIL_VIEWF
    , C.EMAIL
    , C.URL
    , CASE WHEN LEN(@MAIN_BIZ) > 0 THEN @MAIN_BIZ ELSE C.MAINBIZ END AS MAINBIZ
    , CASE WHEN D.PUB_LOGO IS NULL THEN '' ELSE 'http://job.findall.co.kr/UploadFiles/Platinum/' + D.PUB_LOGO END AS PUB_LOGO
    , PAPER_NEW.[dbo].[fn_DelSpecCharTitle](A.TITLE,'E') AS TITLE
    , E.EC_CHOBO
    , E.EC_JUBU
    , E.EC_JANGNYUN
    , E.EC_JANGAE
    , E.EC_HUHAK
    , E.EC_WOIKUK
    , E.EC_GYOPO
    , E.EC_DONGJONG
    , E.EC_ENGLISH
    , E.EC_CHINESE
    , E.EC_AUTOLICENSE
    , E.EC_BIKELICENSE
    , E.EC_CAROWNER
    , E.EC_COMPUTER
    , E.EC_LONGTIME
    , E.EC_INGUNE
    , E.EC_ABOUTLICENSE
    , E.EC_ARMY
    , E.EC_SUKSIK
    , E.EX_SUBWORK
    , A.FIELD_3
    , C.SEXF
    , C.AGEF
    , C.AGEFROM
    , C.AGETO
    , C.AGESUB_JUBU
    , C.AGESUB_MIDDLE
    , C.AGESUB_MINORITY
    , C.EDULEVEL
    , C.CAREERF
    , C.CAREERFROM
    , C.CAREERTO
    , C.WORK_MAIN
    , C.WORK_SUB
    , C.WORK_OUT
    , C.PARTTIMEF
    , C.WORKTIMEF
    , C.WORKTIMEFROM
    , C.WORKTIMETO
    , C.PAYF
    , C.PAYFROM
    , C.PAYTO
    , C.PAYTYPE
    , CASE WHEN LEN(@HOMEPAGE) > 0 THEN C.HOMEF END AS HOMEF
    , B.EX_CONTENTS
    , A.START_DT
    , A.END_DT
    , C.REGULAREMPF
    , C.ONLINEF
    , C.EMAILF
    , C.MOBILEF
    , C.PHONEF
    , C.URLF
    , C.VISITF
    , C.SUBMIT_DOC
    , C.CI_ZIPID
    , C.CI_ADDRDETAIL
    , J.Metro AS CI_AREA_A
       , J.City AS CI_AREA_B
       , J.Dong AS CI_AREA_C
    , (CASE WHEN LEN(@METRO) > 0 THEN
       @METRO + (CASE WHEN LEN(@CITY) > 0 THEN ' ' + @CITY + (CASE WHEN LEN(@DONG) > 0 THEN ' ' + @DONG ELSE '' END) ELSE '' END)
     ELSE
       (CASE WHEN C.CI_ZIPID > 0 THEN J.Metro + ' ' + J.City + ' ' + J.Dong + ' ' + C.CI_ADDRDETAIL ELSE '' END)
     END) AS COMPANY_ADDR
     , C.AGE
        , C.ADDRESS_JIBUN
        , C.ADDRESS_ROAD
        , C.ADDRESS_DETAIL
  , B.GMAP_X
  , B.GMAP_Y
  , C.PAY_POSSIBLE
  , C.WORK_FREELANCER
  , C.PAY_COMPANY_RULES
  , C.PAY_COMPANY_RULES_ETC
  , C.FAX
  , C.FAXF
  , C.DAY_WEEK
  , C.DAY_WEEK_OPTION
  , C.DAY_WEEK_OPTION_ETC
  , C.CI_BIZNO
  , C.WORKTIMEDISPLAY
  , C.DAY_WEEK_OPTION2
  , C.RESTTIMEF
  , C.REAL_WORKTIME
  , C.REAL_WORKTIMEDISPLAY
  , C.WORKTIME_CODE
  , C.PAYTO_OVERF
  , C.WORK_TAKE_CHARGE
  , C.COMPANY_URL
  , C.MAP_VIEW_YN
  , C.OUTF
  , C.RECRUIT_END_DT
 FROM API_LINE_AD_TB A (NOLOCK)
 JOIN API_LINE_AD_EXTEND_DETAIL_TB B (NOLOCK) ON B.LINEADNO = A.LINEADNO
 JOIN API_LINE_AD_EXTEND_DETAIL_JOB_TB C (NOLOCK) ON C.LINEADNO = A.LINEADNO
 LEFT JOIN API_LOGO_OPTION_TB D (NOLOCK) ON D.LINEADNO = A.LINEADNO
 LEFT JOIN API_AD_EC_DATA_JOB_TB E (NOLOCK) ON E.LINEADNO = A.LINEADNO
 LEFT JOIN PAPERREG.DBO.ZIPCODE J (NOLOCK) ON J.ZipId = C.CI_ZIPID
 WHERE A.LINEADNO = @lineadno

 SELECT A.LINEADNO
    , A.FINDCODE
	, A.FINDCODE_NEW --업직종 개편으로 인한 신규 코드 추가 
    , A.[ORDER]
 FROM API_LINE_AD_FINDCODE_TB A
 WHERE A.LINEADNO = @lineadno
 ORDER BY A.[ORDER]


 SELECT A.LINEADNO
    , A.AREA_A
    , A.AREA_A_CODE
    , A.AREA_B
    , A.AREA_B_CODE
    , A.AREA_C
    , A.AREA_C_CODE
    , A.[ORDER]
    , A.AREA_DETAIL
 FROM API_LINE_AD_AREA_TB A
 --LEFT JOIN [PAPER_NEW].[DBO].[CM_ZIPTXT_CODE] C ON C.AREA_C_CODE = A.AREA_C_CODE
 WHERE A.LINEADNO = @lineadno
   --AND A.[ORDER] < 100 
 ORDER BY A.[ORDER]


 SELECT A.LINEADNO
    , A.SUBWAY_CODE
    , A.GATE_NUMBER
    , A.ETC
    , A.[ORDER]
 FROM API_AD_SUBWAY_DATA_TB A
 WHERE A.LINEADNO = @lineadno
 ORDER BY A.[ORDER]


END
GO










USE [PARTNERSHIP]
GO

/****** Object:  Table [dbo].[API_LOGO_OPTION_TB]    Script Date: 2023-02-22 오전 11:12:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[API_LOGO_OPTION_TB](
	[LINEADNO] [char](16) NOT NULL,
	[PUB_LOGO] [varchar](200) NULL,
 CONSTRAINT [PK_API_LOGO_OPTION_TB] PRIMARY KEY CLUSTERED 
(
	[LINEADNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO






USE [PARTNERSHIP]
GO

/****** Object:  Table [dbo].[API_LINE_AD_TB]    Script Date: 2023-02-22 오전 11:13:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[API_LINE_AD_TB](
	[LINEADNO] [char](16) NOT NULL,
	[LINEADID] [int] NOT NULL,
	[INPUT_BRANCH] [tinyint] NOT NULL,
	[LAYOUT_BRANCH] [tinyint] NOT NULL,
	[GROUP_CD] [tinyint] NULL,
	[ORDER_NAME] [varchar](30) NULL,
	[FIELD_3] [varchar](100) NULL,
	[FIELD_6] [varchar](100) NULL,
	[START_DT] [datetime] NULL,
	[END_DT] [datetime] NULL,
	[VERSION] [char](1) NOT NULL,
	[REG_DT] [datetime] NOT NULL,
	[MOD_DT] [datetime] NULL,
	[TITLE] [varchar](500) NULL,
	[ORDER_EMAIL] [varchar](50) NULL,
	[PHONE] [varchar](127) NOT NULL,
	[PHONE_MOBILE] [varchar](127) NULL,
	[VNSNO] [varchar](127) NULL,
	[IDENTYFLAG] [char](1) NOT NULL,
	[FREE_AD_F] [tinyint] NULL,
	[ALBA_PARTNER] [tinyint] NULL,
	[KINFA_PARTNER] [tinyint] NULL,
	[SENIORTV_PARTNER] [tinyint] NOT NULL,
 CONSTRAINT [PK_API_LINE_AD_TB] PRIMARY KEY NONCLUSTERED 
(
	[LINEADNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[API_LINE_AD_TB] ADD  CONSTRAINT [DF_API_LINE_AD_TB_REG_DT]  DEFAULT (getdate()) FOR [REG_DT]
GO

ALTER TABLE [dbo].[API_LINE_AD_TB] ADD  CONSTRAINT [DF_API_LINE_AD_TB_IDENTYFLAG]  DEFAULT ('1') FOR [IDENTYFLAG]
GO

ALTER TABLE [dbo].[API_LINE_AD_TB] ADD  DEFAULT ((0)) FOR [FREE_AD_F]
GO

ALTER TABLE [dbo].[API_LINE_AD_TB] ADD  DEFAULT ((0)) FOR [ALBA_PARTNER]
GO

ALTER TABLE [dbo].[API_LINE_AD_TB] ADD  DEFAULT ((0)) FOR [KINFA_PARTNER]
GO

ALTER TABLE [dbo].[API_LINE_AD_TB] ADD  DEFAULT ((0)) FOR [SENIORTV_PARTNER]
GO







USE [PARTNERSHIP]
GO

/****** Object:  Table [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB]    Script Date: 2023-02-22 오전 11:13:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB](
	[LINEADNO] [char](16) NOT NULL,
	[SUBWAYF] [tinyint] NOT NULL,
	[SUBWAYLINE] [varchar](20) NULL,
	[SUBWAYNAME] [varchar](60) NULL,
	[SUBWAYCODE] [char](14) NULL,
	[AGE] [tinyint] NOT NULL,
	[SEXF] [tinyint] NOT NULL,
	[PAYF] [tinyint] NOT NULL,
	[PAYFROM] [int] NULL,
	[PAYTO] [int] NULL,
	[WORKTIMEF] [tinyint] NOT NULL,
	[WORKTIMEFROM] [int] NULL,
	[WORKTIMETO] [int] NULL,
	[HOMEF] [tinyint] NULL,
	[PARTTIMEF] [tinyint] NULL,
	[WEEKENDF] [tinyint] NULL,
	[PHONEF] [tinyint] NOT NULL,
	[PHONE] [varchar](127) NULL,
	[EMAILF] [tinyint] NULL,
	[EMAIL] [varchar](60) NULL,
	[MOBILEF] [tinyint] NULL,
	[MOBILE] [varchar](127) NULL,
	[URLF] [tinyint] NULL,
	[URL] [varchar](60) NULL,
	[RECRUIT_END_DT] [smalldatetime] NULL,
	[AD_KIND] [char](1) NOT NULL,
	[PHONE1_VIEWF] [bit] NOT NULL,
	[PHONE1] [varchar](127) NULL,
	[PHONE2_VIEWF] [bit] NOT NULL,
	[PHONE2] [varchar](127) NULL,
	[EMAIL_VIEWF] [bit] NOT NULL,
	[AGEF] [tinyint] NOT NULL,
	[AGEFROM] [int] NOT NULL,
	[AGETO] [int] NOT NULL,
	[AGESUB_JUBU] [tinyint] NOT NULL,
	[AGESUB_MIDDLE] [tinyint] NOT NULL,
	[AGESUB_MINORITY] [tinyint] NOT NULL,
	[MAINBIZ] [varchar](100) NULL,
	[EDULEVEL] [tinyint] NOT NULL,
	[CAREERF] [tinyint] NOT NULL,
	[CAREERFROM] [int] NOT NULL,
	[CAREERTO] [int] NOT NULL,
	[WORK_MAIN] [tinyint] NOT NULL,
	[WORK_SUB] [tinyint] NOT NULL,
	[WORK_OUT] [tinyint] NOT NULL,
	[PAYTYPE] [tinyint] NOT NULL,
	[REGULAREMPF] [tinyint] NOT NULL,
	[VISITF] [tinyint] NOT NULL,
	[CI_ZIPID] [int] NOT NULL,
	[CI_ADDRDETAIL] [varchar](100) NULL,
	[ONLINEF] [tinyint] NOT NULL,
	[SERVICE_PERIOD] [tinyint] NULL,
	[SUBMIT_DOC] [tinyint] NOT NULL,
	[WORK_APPOINT] [tinyint] NOT NULL,
	[ADDRESS_JIBUN] [varchar](200) NULL,
	[ADDRESS_ROAD] [varchar](200) NULL,
	[ADDRESS_DETAIL] [varchar](200) NULL,
	[PAY_POSSIBLE] [tinyint] NOT NULL,
	[WORK_FREELANCER] [tinyint] NOT NULL,
	[PAY_COMPANY_RULES] [tinyint] NOT NULL,
	[PAY_COMPANY_RULES_ETC] [varchar](50) NULL,
	[FAX] [varchar](127) NULL,
	[FAXF] [tinyint] NOT NULL,
	[DAY_WEEK] [tinyint] NOT NULL,
	[DAY_WEEK_OPTION] [int] NOT NULL,
	[DAY_WEEK_OPTION_ETC] [varchar](50) NULL,
	[CI_BIZNO] [varchar](10) NULL,
	[WORKTIMEDISPLAY] [tinyint] NOT NULL,
	[DAY_WEEK_OPTION2] [int] NOT NULL,
	[RESTTIMEF] [tinyint] NOT NULL,
	[REAL_WORKTIME] [smallint] NOT NULL,
	[REAL_WORKTIMEDISPLAY] [tinyint] NOT NULL,
	[WORKTIME_CODE] [tinyint] NOT NULL,
	[PAYTO_OVERF] [tinyint] NOT NULL,
	[WORK_TAKE_CHARGE] [varchar](200) NULL,
	[COMPANY_URL] [varchar](250) NULL,
	[MAP_VIEW_YN] [char](1) NOT NULL,
	[OUTF] [tinyint] NULL,
 CONSTRAINT [PK_API_LINE_AD_EXTEND_DETAIL_JOB_TB] PRIMARY KEY CLUSTERED 
(
	[LINEADNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_PHONEF]  DEFAULT ((1)) FOR [PHONEF]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ('L') FOR [AD_KIND]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_PHONE1_VIEWF]  DEFAULT ((1)) FOR [PHONE1_VIEWF]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_PHONE2_VIEWF]  DEFAULT ((1)) FOR [PHONE2_VIEWF]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_EMAIL_VIEWF]  DEFAULT ((1)) FOR [EMAIL_VIEWF]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_AGEF]  DEFAULT ((100)) FOR [AGEF]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_AGEFROM]  DEFAULT ((0)) FOR [AGEFROM]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_AGETO]  DEFAULT ((0)) FOR [AGETO]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_AGESUB_JUBU]  DEFAULT ((0)) FOR [AGESUB_JUBU]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_AGESUB_MIDDLE]  DEFAULT ((0)) FOR [AGESUB_MIDDLE]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_AGESUB_MINORITY]  DEFAULT ((0)) FOR [AGESUB_MINORITY]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_EDULEVEL]  DEFAULT ((100)) FOR [EDULEVEL]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_CAREERF]  DEFAULT ((100)) FOR [CAREERF]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_CAREERFROM]  DEFAULT ((0)) FOR [CAREERFROM]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_CAREERTO]  DEFAULT ((0)) FOR [CAREERTO]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_WORK_MAIN]  DEFAULT ((0)) FOR [WORK_MAIN]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_WORK_SUB]  DEFAULT ((0)) FOR [WORK_SUB]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_WORK_OUT]  DEFAULT ((0)) FOR [WORK_OUT]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_PAYTYPE]  DEFAULT ((0)) FOR [PAYTYPE]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_REGULAREMPF]  DEFAULT ((0)) FOR [REGULAREMPF]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_VISITF]  DEFAULT ((0)) FOR [VISITF]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  CONSTRAINT [DF_API_LINE_AD_EXTEND_DETAIL_JOB_TB_CI_ZIPID]  DEFAULT ((0)) FOR [CI_ZIPID]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((0)) FOR [ONLINEF]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((0)) FOR [SUBMIT_DOC]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((0)) FOR [WORK_APPOINT]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((0)) FOR [PAY_POSSIBLE]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((0)) FOR [WORK_FREELANCER]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((0)) FOR [PAY_COMPANY_RULES]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((1)) FOR [FAXF]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((0)) FOR [DAY_WEEK]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((0)) FOR [DAY_WEEK_OPTION]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((0)) FOR [WORKTIMEDISPLAY]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((0)) FOR [DAY_WEEK_OPTION2]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((0)) FOR [RESTTIMEF]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((0)) FOR [REAL_WORKTIME]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((0)) FOR [REAL_WORKTIMEDISPLAY]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((0)) FOR [WORKTIME_CODE]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((0)) FOR [PAYTO_OVERF]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ('Y') FOR [MAP_VIEW_YN]
GO

ALTER TABLE [dbo].[API_LINE_AD_EXTEND_DETAIL_JOB_TB] ADD  DEFAULT ((0)) FOR [OUTF]
GO









USE [PARTNERSHIP]
GO

/****** Object:  Table [dbo].[API_LINE_AD_AREA_TB]    Script Date: 2023-02-22 오전 11:14:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[API_LINE_AD_AREA_TB](
	[LINEADNO] [char](16) NOT NULL,
	[AREA_A] [varchar](30) NOT NULL,
	[AREA_B] [varchar](30) NOT NULL,
	[AREA_C] [varchar](30) NOT NULL,
	[AREA_DONG] [varchar](30) NULL,
	[AREA_DETAIL] [varchar](200) NULL,
	[ORDER] [tinyint] NOT NULL,
	[AD_KIND] [char](1) NOT NULL,
	[AREA_C_CODE] [int] NOT NULL,
	[AREA_C_GROUP] [int] NOT NULL,
	[AREA_B_TEMP] [varchar](30) NULL,
	[AREA_C_TEMP] [varchar](30) NULL,
	[AREA_A_CODE] [tinyint] NOT NULL,
	[AREA_B_CODE] [smallint] NOT NULL,
	[AREA_A_TEMP] [varchar](30) NULL,
	[LIVEYN] [char](1) NULL,
 CONSTRAINT [PK_API_LINE_AD_AREA_TB_1] PRIMARY KEY NONCLUSTERED 
(
	[LINEADNO] ASC,
	[ORDER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[API_LINE_AD_AREA_TB] ADD  CONSTRAINT [DF_API_LINE_AD_AREA_TB_ORDER]  DEFAULT ((1)) FOR [ORDER]
GO

ALTER TABLE [dbo].[API_LINE_AD_AREA_TB] ADD  CONSTRAINT [DF__PP_LINE_A__AD_KI__1EE55101]  DEFAULT ('L') FOR [AD_KIND]
GO

ALTER TABLE [dbo].[API_LINE_AD_AREA_TB] ADD  DEFAULT ((0)) FOR [AREA_C_CODE]
GO

ALTER TABLE [dbo].[API_LINE_AD_AREA_TB] ADD  DEFAULT ((0)) FOR [AREA_C_GROUP]
GO

ALTER TABLE [dbo].[API_LINE_AD_AREA_TB] ADD  DEFAULT ((0)) FOR [AREA_A_CODE]
GO

ALTER TABLE [dbo].[API_LINE_AD_AREA_TB] ADD  DEFAULT ((0)) FOR [AREA_B_CODE]
GO

ALTER TABLE [dbo].[API_LINE_AD_AREA_TB] ADD  DEFAULT ('Y') FOR [LIVEYN]
GO






USE [PARTNERSHIP]
GO

/****** Object:  Table [dbo].[API_AD_EC_DATA_JOB_TB]    Script Date: 2023-02-22 오전 11:14:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[API_AD_EC_DATA_JOB_TB](
	[LINEADNO] [char](16) NOT NULL,
	[EC_CHOBO] [bit] NOT NULL,
	[EC_JUBU] [bit] NOT NULL,
	[EC_JANGNYUN] [bit] NOT NULL,
	[EC_JANGAE] [bit] NOT NULL,
	[EC_HUHAK] [bit] NOT NULL,
	[EC_WOIKUK] [bit] NOT NULL,
	[EC_GYOPO] [bit] NOT NULL,
	[EC_DONGJONG] [bit] NOT NULL,
	[EC_ENGLISH] [bit] NOT NULL,
	[EC_CHINESE] [bit] NOT NULL,
	[EC_AUTOLICENSE] [bit] NOT NULL,
	[EC_BIKELICENSE] [bit] NOT NULL,
	[EC_CAROWNER] [bit] NOT NULL,
	[EC_COMPUTER] [bit] NOT NULL,
	[EC_LONGTIME] [bit] NOT NULL,
	[EC_INGUNE] [bit] NOT NULL,
	[EC_ABOUTLICENSE] [bit] NOT NULL,
	[EC_ARMY] [bit] NOT NULL,
	[EC_SUKSIK] [bit] NOT NULL,
	[EX_SUBWORK] [bit] NOT NULL,
	[AD_KIND] [char](1) NOT NULL,
	[LIVEYN] [char](1) NOT NULL,
 CONSTRAINT [PK_API_AD_EC_DATA_JOB_TB] PRIMARY KEY CLUSTERED 
(
	[LINEADNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_CHOBO]  DEFAULT ((0)) FOR [EC_CHOBO]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_JUBU]  DEFAULT ((0)) FOR [EC_JUBU]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_JANGNYUN]  DEFAULT ((0)) FOR [EC_JANGNYUN]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_JANGAE]  DEFAULT ((0)) FOR [EC_JANGAE]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_HUHAK]  DEFAULT ((0)) FOR [EC_HUHAK]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_WOIKUK]  DEFAULT ((0)) FOR [EC_WOIKUK]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_GYOPO]  DEFAULT ((0)) FOR [EC_GYOPO]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_DONGJONG]  DEFAULT ((0)) FOR [EC_DONGJONG]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_ENGLISH]  DEFAULT ((0)) FOR [EC_ENGLISH]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_CHINESE]  DEFAULT ((0)) FOR [EC_CHINESE]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_AUTOLICENSE]  DEFAULT ((0)) FOR [EC_AUTOLICENSE]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_BIKELICENSE]  DEFAULT ((0)) FOR [EC_BIKELICENSE]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_CAROWNER]  DEFAULT ((0)) FOR [EC_CAROWNER]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_COMPUTER]  DEFAULT ((0)) FOR [EC_COMPUTER]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_LONGTIME]  DEFAULT ((0)) FOR [EC_LONGTIME]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_INGUNE]  DEFAULT ((0)) FOR [EC_INGUNE]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_ABOUTLICENSE]  DEFAULT ((0)) FOR [EC_ABOUTLICENSE]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_ARMY]  DEFAULT ((0)) FOR [EC_ARMY]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EC_SUKSIK]  DEFAULT ((0)) FOR [EC_SUKSIK]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_EX_SUBWORK]  DEFAULT ((0)) FOR [EX_SUBWORK]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  CONSTRAINT [DF_API_AD_EC_DATA_JOB_TB_AD_KIND]  DEFAULT ('L') FOR [AD_KIND]
GO

ALTER TABLE [dbo].[API_AD_EC_DATA_JOB_TB] ADD  DEFAULT ('Y') FOR [LIVEYN]
GO





USE [PARTNERSHIP]
GO

/****** Object:  Table [dbo].[API_AD_SUBWAY_DATA_TB]    Script Date: 2023-02-22 오전 11:14:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[API_AD_SUBWAY_DATA_TB](
	[LINEADNO] [char](16) NOT NULL,
	[SUBWAY_CODE] [varchar](14) NOT NULL,
	[GATE_NUMBER] [varchar](20) NULL,
	[ETC] [varchar](128) NULL,
	[ORDER] [tinyint] NOT NULL,
	[AD_KIND] [char](1) NOT NULL,
	[LIVEYN] [char](1) NOT NULL,
 CONSTRAINT [PK_API_AD_SUBWAY_DATA_TB] PRIMARY KEY CLUSTERED 
(
	[LINEADNO] ASC,
	[ORDER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[API_AD_SUBWAY_DATA_TB] ADD  CONSTRAINT [DF_API_AD_SUBWAY_DATA_TB_ORDER]  DEFAULT ((1)) FOR [ORDER]
GO

ALTER TABLE [dbo].[API_AD_SUBWAY_DATA_TB] ADD  CONSTRAINT [DF_API_AD_SUBWAY_DATA_TB_AD_KIND]  DEFAULT ('L') FOR [AD_KIND]
GO

ALTER TABLE [dbo].[API_AD_SUBWAY_DATA_TB] ADD  DEFAULT ('Y') FOR [LIVEYN]
GO



